### ISSUE TITLE
Optimization passes should use Add* instruction methods on IRContext rather than on Module.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1000]
Those module methods should be marked deprecated for use by things other than the IRContext.

I'm not sure if we should go so far as hiding the Module methods and instead making the IRContext a friend of Module.

**Comment by dnovillo** [comment]
Yes.  Forcing everything to go through IRContext is the way to go, IMO.  We can add friend declarations as needed.

Another concern I have is the invalidation of analyses.  It should be impossible for a pass to invalidate an analysis without IRContext finding about it.  I'm not totally convinced this is currently true.  I think it's true, but perhaps @s-perron can comment on this.

**Comment by s-perron** [comment]
I had thought about hiding the module's version of these functions when I created the IRContext.  The reason I did not was that I still wanted us to be able to create a module without having an IRContext.  However, we can decide what we want to do with that.  I don't have strong feelings about what we do.

Yes Diego, you are correct.  It is still possible for people to mess up the analyses because they did not inform the IRContext.  I don't know all of the ways, but the main ones are adding an instruction to a basic block using the methods in the BasicBlock class, and inserting and instruction after (or before) another using the methods in the instruction class.  Now that they are both aware of their context, it should be easy to fix that up.
