### ISSUE TITLE
Structured buffers in Spiregg

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1096]
When dealing with structured buffers, local resources have to map back to a global resource.  This "mapping" happens by essentially doing copy propagation in the optimizer.  The problem we have is how do we represent these objects so they can be propagated.  The way that textured are represented has worked well because when loading an OpImage it acts like a pointer. But for structured buffer we have a couple problems.  The example below show these two issues.

```
struct S {
    float4 f;
};

RWStructuredBuffer<S> gRWSBuffer;

float4 main() : A {
    RWStructuredBuffer<S> t;

    gRWSBuffer[0].f = 0.;
    t = gRWSBuffer;
    gRWSBuffer[0].f = 1.;

    return t[0].f;
}
```

Suppose the copy from `gRWSBuffer` to `t` is treated as a "deep copy"  Then entire array is copied.  This will give the following code for the copy:

```
         %38 = OpLoad %type_StructuredBuffer_S %gRWSBuffer  
               OpStore %T %38
```

Then the load at the end will be something like (I know this is not exact):

```
         %59 = OpAccessChain %_ptr_Function_S_0 %t %int_0 %int_0
         %60 = OpLoad %S_0 %59
```

What we want is in the OpAccessChain to replace `%t` with `%gRWBuffer`.  Without considering the store to `gRWSBuffer`, this propagation is legal, but not because `%t` and `%gRWBuffer` are equal--they are pointer that point to different locations.  It is legal because objects that they point to have the same value.  

We do not have any optimizations that can currently do this.  We could try removing the access chain by loading the whole buffer, and then use an OpCompositeExtract, except that the index to a structured buffer are not typically literals.  This means that current optimizations will not work.

Now if we consider the stores to gRWSBuffer, we run into a much more serious problem: the deep copy is semantically wrong.  The important question to ask is which value is returned 0 or 1?  The correct answer is 1, based on looking at the output from fxc. This means that the copy to `t` is really just copying some type of handle.

This leads to my proposed solution: Private and Function storage class structured buffers will be represented as pointer to the global object.  Then the legalization problem will be copy propagate the pointers.  This creates new cases that existing optimizations have to handle: in a shader there will be pointers to pointers to structured buffers.

The entire flow will come in three main steps:

1. Spiregg generates SPIR-V shaders that conform to this relaxed logical addressing mode.
2. A series of optimizations that are aware of shaders with the relax addressing mode are run in order to optimize away all of these pointers to pointers.  This is the legalization phase.  The set of optimizations cannot be changed by the user.
3. Now we should have a valid shader with logical address, and we can do any other optimization for performance.  This is the optimization phase, and it is optional.  Given set of optimization that are run can be modified by the user using command line options.

Spiregg will start to emit this type of code with PRs:

https://github.com/Microsoft/DirectXShaderCompiler/pull/918
https://github.com/Microsoft/DirectXShaderCompiler/pull/923
https://github.com/Microsoft/DirectXShaderCompiler/pull/929

They are waiting for spirv-opt to be able to leagalize the code before merging.

**Comment by s-perron** [comment]
@antiagainst Please correct anything I said that is incorrect.

**Comment by antiagainst** [comment]
Thanks for the nice write up, @s-perron! The above is correct to my knowledge.

By structured buffer, we actually mean the following HLSL resource types:

* StructuredBuffer
* RWStructuredBuffer
* AppendStructuredBuffer
* ConsumeStructuredBuffer
* ByteAddressBuffer
* RWByteAddressBuffer

Non-externally-visible HLSL variables of these types will be put  into SPIR-V `Private` or `Function` storage class. These variables should be treated as **aliases** to some global external ones and their uses should be replaced by the uses of corresponding global external resources via legalization transformations.

cc @ehsannas @chaoticbob

**Comment by dneto0** [comment]
Let me see if I understand:

* All these HLSL types map to a Vulkan uniform buffer or storage buffer.   
* Uniform buffers and storage buffers are module-scope objects, which is why you can infer that such an object of that type declared inside a function should always be considered as something that will only point (a) nothing or (b) an object of the same type but declared at module scope.  That's why it's ok to make the function-scope definition be the definition of a pointer-to-*-buffer.

I think you should also clarify the intended flow is to have multiple phases:
* First phase is initial code generation from HLSL:  It will map these function-scope variables of the special types to pointer-to-*-buffer in SPIR-V.  This is invalid SPIR-V for Vulkan which must be later reduced.
* Second phase runs SPIR-V transforms that understand this "relaxed" form of logical addressing, the purpose is to eliminate these extra (invalid-for-Vulkan) pointer-to-*-buffer variables.
* Third phase: the module is valid SPIR-V for Vulkan.

Also, if this works for all the cases we're seeing, then I think we'll ask Glslang to adopt the same compilation scheme and transforms scheme (i.e. phases 1 and 2 should match between DXC/Spiregg and Glslang)

**Comment by s-perron** [comment]
@dneto0 Yes, that is the proper understanding.  I've updated the first comment to reflect the different phases.

**Comment by antiagainst** [comment]
@dneto0: Yep.

A **local** resource (in the `Private` or `Function` storage class) must map to some **global** resource (in the `Uniform` storage class), after function inlining, copy propagation, DCE, etc. Otherwise, the source code should be rejected. This is the behavior for both fxc and dxc.

So, for all such structured/byte buffer objects declared as the following:

* static global
* static function local
* function local
* function parameter
* function return

They will be generated as of pointer-to-pointer type to indicate that they are aliases.

Note that the following types has associated counters that are translated into **separate** OpVariables:

* RWStructuredBuffer
* AppendStructuredBuffer
* ConsumeStructuredBuffer

All the associated counters should be handled in parallel to their parent buffer objects.

**Comment by greg-lunarg** [comment]
What fxc command line did you use to compile the shader above?

**Comment by antiagainst** [comment]
@greg-lunarg: `fxc.exe -T vs_5_1 <input-name>`:

```
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Note: shader requires additional functionality:
//       UAVs at every shader stage
//
//
// Buffer Definitions:
//
// Resource bind info for gRWSBuffer
// {
//
//   struct S
//   {
//
//       float4 f;                      // Offset:    0
//
//   } $Element;                        // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gRWSBuffer                            UAV  struct         r/w      U0             u0      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// A                        0   xyzw        0     NONE   float   xyzw
//
vs_5_1
dcl_globalFlags refactoringAllowed
dcl_uav_structured U0[0:0], 16, space=0
dcl_output o0.xyzw
store_structured U0[0].xyzw, l(0), l(0), l(0,0,0,0)
store_structured U0[0].xyzw, l(0), l(0), l(1.000000,1.000000,1.000000,1.000000)
ld_structured o0.xyzw, l(0), l(0), U0[0].xyzw
ret
// Approximately 4 instruction slots used
```

**Comment by s-perron** [comment]
From a DXC perspective, all of this work is done.
