### ISSUE TITLE
Should iterators be preferred over ForEach* methods ?

### ISSUE THREAD

**Issue by Naghasan** [KhronosGroup/SPIRV-Tools#1151]
Many data structures have `ForEach*` methods instead of iterators, but this does not play well with the C++ library.

Very simple example from the BasicBlock class:
```
  // Returns true if this basic block has any Phi instructions.
  bool HasPhiInstructions() {
    int count = 0;
    ForEachPhiInst([&count](ir::Instruction*) {
      ++count;
      return;
    });
    return count > 0;
  }
```
Could be expressed as:
```
bool HasPhiInstructions() {
  return phi_begin() != phi_end();
}
```

One issue I find with this "ForEach" approach is that it prevents early exits, many are over small intervals (so that's fine) but that's not always the case.

Should we try to favor iterator implementation (which takes more time) over "ForEach" (quicker to implement but limits/prevents the C++ library usage)

**Comment by dnovillo** [comment]
I personally prefer standard iterators over ForEach.  It also prevents the somewhat hideous lambda syntax.

**Comment by dneto0** [comment]
The early exit behaviour could be addressed by having the lambda return a value to indicate "continue" vs. "exit now".   We haven't done that (yet) because it makes the common case more complex, unless the early exit form is another method name or templated differently.

But that doesn't address your other criticism.

Then again:
 - someone would have to implement the phi_begin, phi_end pair.     You've just hidden the complexity
 - using iterators introduces the complexity of understanding when they are invalidated.  (This is a general problem with iterators).

But yes, the overwhelming C++ common use is to use iterators.   Even that might be a historic accident because lambdas came later than iterators.

**Comment by dj2** [comment]
Why not just return the vector or whatever data structure the phi is stored in and let the user decide how they want to use it?

**Comment by s-perron** [comment]
We have added `while_each` which allow for early exits. Rewriting to use iterator is not something we believe it worth the effort at this time.
