### ISSUE TITLE
Request to re-install InsertExtractElim in LegalizationPasses

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#1326]
"Legalization" has been used to describe optimizations which are needed to "fix" SPIR-V generated by front-ends from HLSL which is illegal for Vulkan. Up to this point in time this has basically comprised propagation of opaque and pointer types. I would like to propose an additional legalization category: dead code elimination (DCE).

Working with a group porting HLSL shaders to Vulkan, they were relying on fxc to remove certain texture samples (and the subsequent references to the textures and samplers involved) through dead code elimination. Failure to remove these samples would cause errors to be generated by the validation layers noting that textures and samplers were being referenced in the shader which were not bound by the application. I would suggest that DCE of these samples constitutes legalization as it allows these shaders to be executed without errors. Parenthetically, removal of these samples (and their dependent code) also made dramatic (>30%) decreases in SPIR-V size and similar reductions in pipeline creation times. 

While the client's code cannot be included, I have constructed a sequence from one of their shaders:

               OpCapability Shader
               OpCapability Sampled1D
               OpCapability SampledCubeArray
               OpCapability SampledBuffer
               OpCapability ImageQuery
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %GBufferFunc "GBufferFunc" %fs_in_m_Color %fs_in_m_Coords %diff_emis
               OpExecutionMode %GBufferFunc OriginUpperLeft
               OpSource HLSL 500

       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v3float = OpTypeVector %float 3
    %v4float = OpTypeVector %float 4
%_ptr_Input_v4float = OpTypePointer Input %v4float
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_ptr_Uniform_float = OpTypePointer UniformConstant %float
          %9 = OpTypeSampler
       %4713 = OpTypeImage %float Cube 0 1 0 1 Unknown
%_ptr_UniformConstant_9 = OpTypePointer UniformConstant %9
       %4718 = OpTypeSampledImage %4713
%_ptr_UniformConstant_4713 = OpTypePointer UniformConstant %4713
    %float_0 = OpConstant %float 0.0
    %float_1 = OpConstant %float 1.0

%g_EnvProbeArray = OpVariable %_ptr_UniformConstant_4713 UniformConstant
%g_LinearClampSampler = OpVariable %_ptr_UniformConstant_9 UniformConstant
%fs_un_m_Lod = OpVariable %_ptr_Uniform_float UniformConstant

%fs_in_m_Color = OpVariable %_ptr_Input_v4float Input
%fs_in_m_Coords = OpVariable %_ptr_Input_v4float Input
  %diff_emis = OpVariable %_ptr_Output_v4float Output

%GBufferFunc = OpFunction %void None %3
          %5 = OpLabel

       %9646 = OpLoad %float %fs_un_m_Lod
       %9517 = OpLoad %v4float %fs_in_m_Coords
       %9518 = OpLoad %4713 %g_EnvProbeArray
       %9519 = OpLoad %9 %g_LinearClampSampler
       %9520 = OpSampledImage %4718 %9518 %9519
       %9523 = OpCompositeExtract %float %9517 0
       %9524 = OpCompositeExtract %float %9517 1
       %9525 = OpCompositeExtract %float %9517 2
       %9526 = OpCompositeConstruct %v4float %9523 %9524 %9525 %float_0
       %9995 = OpImageSampleExplicitLod %v4float %9520 %9526 Lod %9646

       %9933 = OpLoad %v4float %fs_in_m_Color

       %9070 = OpCompositeExtract %float %9933 0
       %9071 = OpCompositeExtract %float %9933 1
       %9072 = OpCompositeExtract %float %9933 2
       %9073 = OpCompositeConstruct %v4float %9070 %9071 %9072 %float_0
       %9078 = OpCompositeConstruct %v4float %float_1 %float_1 %float_1 %float_0
      %10004 = OpExtInst %v4float %1 FMix %9995 %9073 %9078
       %9107 = OpVectorShuffle %v3float %10004 %10004 0 1 2
      %18595 = OpCompositeExtract %float %9107 0
      %18596 = OpCompositeExtract %float %9107 1
      %18597 = OpCompositeExtract %float %9107 2
      %18598 = OpCompositeConstruct %v4float %18595 %18596 %18597 %float_1
               OpStore %diff_emis %18598
               OpReturn
               OpFunctionEnd

Note that the OpImageSampleExplicitLod instruction (and much of the code it depends on including the texture and sampler definitions) can be removed.

Recently InsertExtractElim was removed from the spirv-opt Legalization passes and replaced with Simplification. InsertExtractElim enables this code to be removed; Simplification does not.

I would further posit that Simplification as it is constituted cannot be incrementally improved to perform the kind of propagation needed for this and similar code.

I would further posit that even if it were possible, the pair-wise nature of the Simplfication pass would require a number of "rules" which would be quadratic in the number of different instructions that can be encountered in such sequences which would "square" the implementation and maintenance required. InsertExtractElim utilizes only one method for each instruction type.

As such, I suggest that InsertExtractElim be re-installed in the legalization passes for users with such shaders. Subsequently, I suggest that the insert/extract optimizations be removed from Simplification as redundant.

I won't claim that InsertExtractElim is the best or the only way to solve the problem of propagation through vector and matrix instructions, but for the moment I think it is the best method we have and I think we need to make it available to users wherever it can help.

**Comment by s-perron** [comment]
Looks like Fmix.  Should be fixed with #1324.  The other area missing from the simplification pass is folding rules involving vector shuffle.  Then it will completely subsume insert extract elimination.

**Comment by greg-lunarg** [comment]
Notice that the "constant" to FMix is not all 1s.  This is the way the client's code reads. So #1324 as it is currently constituted, will not address this code sequence.

**Comment by s-perron** [comment]
Sorry a bit too quick.  #1324 will not help this case because the vector in the mix instruction is not all 1's or 0's.  However, I will try to give a more complete response.

1) Sorry I should not have removed insert-extract elimination until it was completely subsumed.  I made a bad assumption that the legalization passes were only being used in DXC.

2) I view insert-extract elimination as a very specific simplification pass, and I do expect it to become part of instruction folding.  With regard to your first point that it cannot be easily implemented using the folding rules I would disagree.  The main part of the insert-extract elimination pass is the `DoExtract` function.  The input is conceptually a decomposed OpCompositeExtract instruction.  It then looks at the instruction feeding that conceptual instruction, and rewrite it if it can.  Then it continues looking at the instructions feeding the new extract instruction.  This is exactly what the folder does.  It looks at an instruction.  Rewrites it based on the instructions feeding it.  After rewritting, it does the same.

3) You suggest that it would need to "square" the implementation.  I disagree.  For the folder to be able to fold these instructions you only need the rules that from an OpCompositeExtract feeding and Insert, VectorShuffle, FMix, CompositeConstruct, and CompositeConstant.  All of which are already done except for VectorShuffle and FMix.  If we add any other rules, it is because they get us other opportunities.

4) We could add insert-extract elimiantion back in until VectorShuffle and Fmix are added to the folding rules.

5) We should not remove any of the folding rules because they are not fully redundant.  They are able to simplify the code in ways that insert-extract elimination cannot.  As one exmaple, notice that `DoExtract` returns a single uint32_t.  This is because insert-extract elimination does not make any changes unless it is able to reduce the extract instruction to a single value.  The simplifier is willing to rewrite the Extract to by-pass instruction potentially making them dead.  For example, the `ConflictingInsertPreventsOptimization2` test in insert_ectract_elim_test.cpp.  If you try that case with instruction simplification and ADCE, notice that you are left with just one load instead of two. (Make sure you include the bug fix #1325).

**Comment by greg-lunarg** [comment]
Regarding 5, yes, InsertExtractElim does not rewrite the extract (yet). But it could. The need just hadn't arisen yet.

The Simplification pass is just fine for constant folding and arithmetic simplification. But it seems problematic to me for propagating values through all the different vector and matrix operations for the reasons I have already outlined.

**Comment by greg-lunarg** [comment]
After some sidebar discussions and learning that the Simplifier (surprisingly) iterates on instruction until closure, it appears that the InsertExtractElim function can be transferred to the Simplifier.

But for now the Simplifier does not cover InsertExtractElim so the recommendation stands to re-install InsertExtractElim until that time.
