### ISSUE TITLE
update_build_version script syntax and str object issues

### ISSUE THREAD

**Issue by bschindler** [KhronosGroup/SPIRV-Tools#144]
I'm trying to build SPIRV-Tools under gentoo linux (with python-3.5) and I run into the following issues: 

[  3%] Update build-version.inc in the Spirv-tools build directory (if necessary).
/usr/bin/python3.5 /home/benjamin/Software/SPIRV-Tools/utils/update_build_version.py /home/benjamin/Software/SPIRV-Tools
  File "/home/benjamin/Software/SPIRV-Tools/utils/update_build_version.py", line 67
    print 'usage: {0} <spirv-tools_dir>'.format(sys.argv[0])
                                       ^
SyntaxError: invalid syntax

I commented out line 67 as it is likely not used during build but then I run into this issue: 

[  3%] Update build-version.inc in the Spirv-tools build directory (if necessary).
/usr/bin/python3.5 /home/benjamin/Software/SPIRV-Tools/utils/update_build_version.py /home/benjamin/Software/SPIRV-Tools
Traceback (most recent call last):
  File "/home/benjamin/Software/SPIRV-Tools/utils/update_build_version.py", line 76, in <module>
    main()
  File "/home/benjamin/Software/SPIRV-Tools/utils/update_build_version.py", line 70, in main
    new_content = ('"spirv-tools ' + describe(sys.argv[1]).replace('"', '\\"') + '\\n"\n')
TypeError: a bytes-like object is required, not 'str'

As my python experience is extremely limited, I thought I should just file this.

**Comment by antiagainst** [comment]
@bschindler: The script is using python2 syntax right now. The `print` error results from [syntax difference between python2 vs. python3](https://docs.python.org/3.0/whatsnew/3.0.html#print-is-a-function).

If you have python2 installed, you may want to change the first line of `utils/update_build_version.py` to `#!/usr/bin/env python2` or symlink your system Python to python2.

Sorry for the inconvenience, we'll fix the issue.

**Comment by bschindler** [comment]
That does explain it. Using python2 did work here. Thanks for the response

**Comment by dekimir** [comment]
Let's keep this open and make the script work for both Python 2 and Python 3.

**Comment by a2flo** [comment]
Note that changing the first line of utils/update_build_version.py to python2 doesn't work when cmake finds python3 and uses it to call the script:
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/CMakeLists.txt#L119 ->
`${PYTHON_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/utils/update_build_version.py`

Doing a `set(Python_ADDITIONAL_VERSIONS 2.7 2.6 2.5)` right before `find_host_package(PythonInterp)` makes it properly use python 2.x (I don't know what the minimum python requirement should be here).
Tested this on latest Arch Linux (which defaults to python3 otherwise) and OS X.

**Comment by antiagainst** [comment]
Right now the script should run under both Python2 & Python3.
