### ISSUE TITLE
spirv-val fails to validate subgroup barriers

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Tools#1469]
[test.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/1897776/test.spv.txt)
`error: 196: ControlBarrier: in Vulkan environment Memory Scope is limited to Device, Workgroup and Invocation`

`--target-env vulkan1.1`

**Comment by sheredom** [comment]
So the language in the Vulkan SPIR-V environment spec for this is here https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/spirvenv.txt#L345

And the offending check in SPIR-V Tools seems to be here https://github.com/sheredom/SPIRV-Tools/blob/master/source/validate_barriers.cpp#L84

I think that check needs to look for vulkan env != 1.0 and allow subgroup scope otherwise.

**Comment by dneto0** [comment]
This is part of a larger problem:  relaxations in Vulkan 1.1 are not reflected in the validator.  We should survey that env spec for conditional text on ifdef::VK_VERSION_1_1[]

**Comment by dneto0** [comment]
I've made a new "milestone" in this project for the *new* validation rules in Vulkan 1.1 env spec, which are *not* direct capability or extension checks.  (Capability and extension checks occur automatically via their encoding in the SPIR-V grammar.)

The milestone is: https://github.com/KhronosGroup/SPIRV-Tools/milestone/3
