### ISSUE TITLE
Vulkan 1.1: FPRoundingMode decoration can only be used with float conversion instructions

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#1482]
https://github.com/KhronosGroup/Vulkan-Docs/blob/master/appendices/spirvenv.txt#L427

**Comment by jaebaek** [comment]
This is unclear to me. SPIR-V spec says

"The **FPRoundingMode** decoration can be applied **only to a width-only conversion instruction** that is used as the Object operand of an OpStore storing through a pointer to a 16-bit floating-point object in the StorageBuffer, Uniform, PushConstant, Input, or Output Storage Classes"

In the unit test named `ValidateData.ext_16bit_storage_caps_allow_free_fp_rounding_mode`, it has the following SPIR-V assembly code:

```
OpDecorate %2 FPRoundingMode RTE
        %1 = OpTypeFloat 32
        %2 = OpConstant %1 1.25
```

Since `OpConstant` is not "a width-only conversion instruction", this SPIR-V assembly code must be invalid. Is it valid code?

**Comment by jaebaek** [comment]
Rebased and pushed into master as 03cbf33a695ec84d41a68333920864876fca18d9
