### ISSUE TITLE
Small size optimizations for vectors

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1609]
In the Instruction class and the Operand, there are std::vector member that typically have  a small number of elements.  For example, the Operand class has a vector of uint32_t to hold the words for that operand.  However, in most cases the number of integers needed for the words is 1.

In this issue, we want to:

- [x] Implement a replacement for std::vector that is optimized for small sizes.
- [x] Looking into using it in the Operand class.
- [x] Look into using it in the Instruction class.
- [ ] Look into using it in the BitVector class.

**Comment by dj2** [comment]
We have a class in PDFium which does the optimization for small sizes and we're trying to get rid of it. In the long run, while it seemed to make thingsy faster, there is a maintenance overhead associated with the class that gets tedious.

We've also found that most cases where that special class was used, we'd get the same, or similar performance gain from reserving and resizing a vector instead of using a fixed size or vector class thing.

**Comment by s-perron** [comment]
@dj2 For the operand class,  the replacement is initialized and then not resized afterwards.  The size is known by the constructor.  I'm assuming it is not faster to do a default construction, reserve, resize, and then copy over the data.  Also these arrays are 1 element 98% of the time.  

We can talk about your suggestions because it could help in other places.

**Comment by s-perron** [comment]
I've tried using the SmallVector class for BitVector to help compile time in vector DCE.  It does not help.  I think some of the profiling I was doing was pointing me in the wrong place.  I'll view this item as done.
