### ISSUE TITLE
Gracefully handle id overflow in spirv-opt

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#1841]
If we have a spir-v module that uses close to the maximum number of ids, it is possible that optimizations will cause the id bound to go over the limit.

At this time, there are no checks that the optimizer does not go past the max id bound.  In fact the current behaviour of `IRContext::TakeNextId()` is to wrap around to 0 after INT_MAX is reached.  Then that value is blindly used by all callers of that function.  It is assumed that it is a valid id.  This needs to be fixed because it can lead to the optimizer failing in strange ways.  See http://crbug.com/873225 for a few examples.

We cannot exit the program in `IRContext::TakeNextId()` or anywhere else in the library code.  We do not want to force the calling program to exit because of an error in spirv-opt.  We need to return control to the caller and let it figure out what it wants to do.

The second issue is to figure out what the limit is suppose to be.  In the [spec](https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#_a_id_limits_a_universal_limits), there is a minimum limit of 0x3FFFFF.  However, since validators have to accept an option to increase that limit, it seems like spirv-opt should not always use that value for the limit.  Should there be an option to set the limit?

**Comment by dneto0** [comment]
I think there are two things to resolve here:

-  Gracefully wrap around

- What to do if we really do run out of IDs and can't make more.

For the graceful wraparound, I would treat it like a stop-the-world garbage collection and be willing to pay a long latency to find the next bunch of free IDs.  For example, refresh the def-use-manager and find the 1000 lowest-numbered unused IDs by scanning (in sequential order) the id-to-def map.

What happens if we really do run out of IDs?   I think we should set a flag in the IR context, and then exit (gracefully?!) out of that pass, and then return an error from the pass manager.  This one is a bit more fuzzy to me since each pass will have its quirks around safe exiting checkpoints.

**Comment by s-perron** [comment]
@dneto0 Any comments on what the limit should be and whether or not there should be an option to change the limit?

**Comment by s-perron** [comment]
@dneto0 @dnovillo @alan-baker @dj2 

I just opened a PR for the first change I made for this issue.  This represents the main method I will use to implement this.  I will have a smallish change that propagates the error up.  Leaving TODOs around to identify where to continue in future PRs.  At each point, things should be getting better.

**Comment by s-perron** [comment]
The general design has been handled.  There will be a error message when there is overflow.  It is up to the pass to determine what to do when there is overflow.  There are many changes that have gone in the past year fixing up individual optimizations.

I will close this issue.  Any new work in this area will be as new failures come up.
