### ISSUE TITLE
Invalid SPIR-V produced with array of textures

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Tools#1860]
I have a simple hlsl shader that results in invalid SPIRV. I sent it to SPIRV-Cross first but it seems the error is in the SPIRV which then propagates into glsl. The unoptimized shader also exhibits this problem, but apparently this is something that unoptimized SPIRV cannot do before legalization. The original bug and discussion is https://github.com/KhronosGroup/SPIRV-Cross/issues/662

The hlsl I used is

```hlsl
TextureCube t0; SamplerState s0;
TextureCube t1; SamplerState s1;

float4 fragmentProgram(float4 input : INPUT0) : SV_Target0
{
	float4 result = 0;

	TextureCube texCubeArray[2];
	texCubeArray[0] = t0;
	texCubeArray[1] = t1;

	[unroll]
	for (int i = 0; i < 2; ++i)
	{
		result += texCubeArray[i].Sample(s0, input.xyz);
	}

	return result;
}
```

the optimization passes I use are the standard performance set that comes with SPIRV-Tools. I'm attaching the resulting SPIRV.

[fragmentProgram_optimized.spv.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/2314452/fragmentProgram_optimized.spv.txt)

**Comment by antiagainst** [comment]
We have loop unroll passes in spirv-opt, but they are not extensively tested yet. They are not integrated into any of the standard recipes. 

This shader has local resource manipulation inside a loop, which surely requires loop unroll in the HLSL legalization recipe.

If you are using DXC, you can make it work by manually tweaking the passes invoked by `-Oconfig=`: `dxc.exe -spirv -T ps_6_0 -E fragmentProgram -Oconfig=--loop-unroll,--legalize-hlsl,-O`, which will run legalization passes first (implicitly by the compiler that you cannot turn off, at least for now), then loop unroll pass, then legalization passes again, and then finally optimization passes. It seems a lot, but later runs of recipe should be fairly quick since most of the work is already done by previous recipe.

**Comment by redorav** [comment]
My SPIR-V is sourced from glslang and all our pipeline is configured that way as we developed it before dxc produced any SPIR-V. However I have control of what passes go into the optimizer. I'll try adding the loop unroll to see if that makes it work.

What passes and at what point in the standard performance recipe would you recommend I insert the passes to get the loop unrolling?

**Comment by antiagainst** [comment]
I think

```
.RegisterLegalizationPasses()
.CreateLoopUnrollPass(...)
.RegisterLegalizationPasses()
.RegisterPerformancePasses()
```
should be good?

But if you want more fine-grained control to avoid duplicates, you may want to do some further experiments. Or @s-perron, @alan-baker, @dnovillo may have better suggestions.

**Comment by s-perron** [comment]
If you want something with fewer optimizations you can look at what I did in https://github.com/s-perron/SPIRV-Tools/commit/2891838c06529496d8d006a308d6c765d8426add.  This was just for expiriements.  

However, Lei's suggestion is probably the simplest and will work well.

**Comment by redorav** [comment]
Yeah that worked well, I'll tweak it a bit probably but the loop unrolling didn't introduce any additional issue and fixed this for me. Thanks a lot!

**Comment by s-perron** [comment]
Great to hear.

**Comment by redorav** [comment]
I ended up copying the performance passes recipe and adding the loop unroll between the CopyPropagateArraysPass and the CreateAggressiveDCEPass like the legalization recipe suggests in a comment. Worked well as I didn't want to make it much more expensive. Closing as fixed.
