### ISSUE TITLE
Improve runtime performance using custom allocator

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/SPIRV-Tools#1947]
On several real world shader collections, we are seeing bad runtime performance on Windows. Among various reasons, memory allocation is a significant factor. Too many small separate memory allocations together consume too much time. STL containers do this, and also other places we have explicit new/delete.

We should consider to have a custom allocator to consolidate small allocations and improve runtime performance.

**Comment by antiagainst** [comment]
Several approaches:

We can pull in some existing allocator, but if incorporating using CMake, it introduces an additional dependency; thus the requirements on toolchain can change.

Copying in the source code needs to have the same license. And typically it will pull in many source files.

Writing our own and make it good is hard.

**Comment by antiagainst** [comment]
I've a tentative implementation of a custom allocator entirely inside SPIRV-Tools and changing STL containers to use the allocator here: https://github.com/KhronosGroup/SPIRV-Tools/pull/1946

**Comment by s-perron** [comment]
We need to set the requirements: 

1) We cannot override new/delete/malloc/free because we are a library.  If the main program does the same, then their allocator will be used.  If they don't then the main program will have to use ours.  This is not good behaviour from a library.

2) If we use an external project, it must the the right lenience, and will have to work with all of the compilers that we support including MSVS 2013.

Think the questions we need to answer here are:

1) Is the time spent allocating or deallocting data?
2) What are the most time consuming data structures to allocate and deallocate?
3) Are there any special characteristics of the data?  For example, are they POD?
4) What are the options for existing memory allocators?
5) What type of memory allocator do we want to use? See https://github.com/mtrebi/memory-allocators for a list and implementation of some basic memory allocators.

**Comment by ratchetfreak** [comment]
6. is there an option to change the problematic container(s) itself.

std::map and std::unordered_map (and the set variants) are both pretty bad due to a few features they need to provide in the standard that force a allocated-node-per-element based implementation (referential consistency and exchanging nodes between containers come to mind). I don't think those features are actually used here. 

Dropping those requirements allow creating for better containers for our purposes.

From a quick look at the pull request most unordered_map and unordered_set are used with a uint32 or a pointer as key and map it to a uint32 or pointer. 

The uint32 will always be the instruction results from the input spirV, those should have enough structure to be exploitable.
