### ISSUE TITLE
spirv-opt segfaults or fails assertion in spvtools::opt::Instruction::GetBaseAddress

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#1962]
SPIRV-Tools-master-linux-Debug/bin/spirv-opt --version
SPIRV-Tools v2018.5-dev a3e3869

On attached .spv file embedded in [shader.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/2463841/shader.zip):

SPIRV-Tools-master-linux-Debug/bin/spirv-opt shader.spv --merge-return --eliminate-dead-code-aggressive -o out.spv
Segmentation fault

With debug build from top of tree:

SPIRV-Tools/cmake-build-debug/tools/spirv-opt shader.spv --merge-return --eliminate-dead-code-aggressive -o out.spv
spirv-opt: /home/afdx/SPIRV-Tools/source/opt/instruction.cpp:162: spvtools::opt::Instruction* spvtools::opt::Instruction::GetBaseAddress() const: Assertion `(IsLoad() || opcode() == SpvOpStore || opcode() == SpvOpAccessChain || opcode() == SpvOpInBoundsAccessChain || opcode() == SpvOpCopyObject || opcode() == SpvOpImageTexelPointer) && "GetBaseAddress should only be called on instructions that take a " "pointer or image."' failed.
Aborted

Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

**Comment by s-perron** [comment]
This is a documented issue in merge return.  I this case there is a loop whose continue block is unreachable, but there is still a conditional branch at the end of the continue block instead of a branch to the head.  This causes problems in the OpPhi generation during merge return.  Being able to correctly handle all of these cases is not reasonable, which is why the description of the merge return option says:

> For structured control flow it is assumed that the only unreachable blocks in the function are trivial merge and continue blocks.
>
> A trivial merge block contains the label and an OpUnreachable instructions, nothing else.  A trivial continue block contain a label and an OpBranch to the header, nothing else.
>
> These conditions are guaranteed to be met after running dead-branch elimination.
