### ISSUE TITLE
Validator: Check new restrictions in WebGPU environment

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#2265]
See https://github.com/gpuweb/spirv-execution-env/pull/8

**Comment by zoddicus** [comment]
I have gone through, checked the status of these, and created issues for the unresolved ones.

From the gpuweb/spirv-execution-env#8:

> Remove capabilities:
> 
> SampledBuffer, ImageBuffer: gpuweb issue 162
Not added to the original whitelist, since they were TBD at the time, so no action needed.

> Remove decorations for various reasons:
> 
> RelaxedPrecision
> Sample
> Invariant
> Coherent
> NoSignedWrap, NoUnsignedWrap
 > FPRoundingMode
Opened new issue #2273. 

> Other:
> Floats and ints are always 32 bits
Opened new issue #2277. 

> Push constant support: open issue for WebGPU
Deferring until final decision has been made.

> No Device scope
Opened new issue #2278. 

> All Function, Private, Output variables require initializers
Opened new issue #2279. 

> Fusing and reassociation of float math cannot be done on NoContraction-decorated operations
This is an optimization issue, but filed #2280 about it.

Also opened an issue, #2276 , about validating the Bultin decoration usages.

**Comment by zoddicus** [comment]
All of the outstanding items from this are either resolved, or tracked in other more specific issues, so closing this.
