### ISSUE TITLE
[spirv-reduce] Accept options to pass to the validator.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/SPIRV-Tools#2396]
DXC generates spir-v files that do not pass the validator unless certains options are pass to it, like `--skip-block-layout`.  However, I do not see how to tell spirv-reduce to use those options when calling the validator.  This means I am undable to use spirv-reduce on those spv files.

**Comment by afd** [comment]
I propose adding a flag, --validator-options=... taking a string to be passed on to the validator, so that you could do:

```
spirv-reduce --validator-options="--skip-block-layout ..." ...
```

Alternatively we could have a flag to disable use of the default validator (e.g. --no-validation), and then the interestingness function could be configured to call the validator in whatever manner is appropriate.

It is probably useful to have the --no-validation option anyway, e.g. so that spirv-reduce could be used to debug the validator, via reducing a valid shader that the validator rejects.  I will file a separate issue for that feature.

**Comment by s-perron** [comment]
How is the validator called?  The options that the validator accepts are not parsed in the library.

**Comment by afd** [comment]
The validator is called via:

```
if (!spvtools::SpirvTools(impl_->target_env).Validate(maybe_result)) {
```

However, we could switch to an overload of Validate that takes spv_validator_options as an argument if needed.

The problem would remain that the options passed in to spirv-reduce would need to be parsed in order to know how to set up the spv_validator_options.

If there are just a few relevant options and they're not expected to change too often, spirv-reduce could mirror them (e.g. providing --validator-skip-block-layout).

**Comment by s-perron** [comment]
Yes the main ones are "skip-block-layout" and "relax-logical-pointer".  @ehsannas Does DXC use any other options internally?
