### ISSUE TITLE
CMake find_host_package(PythonInterp 3 REQUIRED) doesn't work on all systems

### ISSUE THREAD

**Issue by DeanoC** [KhronosGroup/SPIRV-Tools#2514]
CMakeList.txt does find_host_package(PythonInterp 3 REQUIRED) to try and ensure python3 is installed for the tests. This doesn't work on some system which have both python 2 and 3 installed. PythonInterp is depeciated. It should be find_host_package(Python3 REQUIRED)

Additionally it should be only be required if the tests are being built.

**Comment by s-perron** [comment]
The suggested solution was added in cmake 3.12.  If we want to use it, we will have to force the use of cmake 3.12.  The kokoro bots are using cmake 3.7.  Updating those will be significant work because we do not control the images that are used.

**Comment by DeanoC** [comment]
Hmm I’d suggest making the requirement to have python 3 only if tests are built then. As it currently stands I couldn’t build the tools on a Windows machine and a Mac without uninstalling Python 2.7 as the current FindPython scripts finds 2.7 and then fails the 3 requirement even if both are installed.

Not being able to build the tests is at least preferable from being able to build the tools at all.

**Comment by s-perron** [comment]
I thought I had responded to this earlier.  We use Python scripts in the main build process too.  We generate files based on the json file found in spirv-headers.  Since Python 2 will be sunset at the end of this year, we have decided to just more on.

I don't know the exact cause of cmake not finding the correct python.  There are two reasons that I know of that can be the cause.

1. Python 2 is in your CMakeCache.txt, and it does not look any further.  To fix this, delete CMakeCache.txt, and rerun cmake.
2. If spirv-tools is included in another cmake project, it is possible that the high level module or another submodule that is included earlier looks for Python without requiring version 3.  In this case it could find Python 2, and then fail when it sees the requirement in spirv-tools.  To fix this, include the python package early in the high level module with the python3 requirement.

Sorry for the delay.

**Comment by DeanoC** [comment]
I think the problem is the old FindPython. it seems to stop at the first python it finds and then does the REQUIRE test. So in my case on both Windows and OSX I tried, if found Python 2.x then checked if it was version 3 and then failed the test, even though python 3 was sitting next to it.
For me I removed Python2 on both machines and it worked fine then but obviously might be  a problem if the user requires both side by side.

I'm guessing that why CMake changed the test function in a cmake 3.12?

**Comment by DeanoC** [comment]
Any way I'll close this, theres several workarounds here and its looks like there is no easy way. Just put it down to the vagaries of cmake and python :)

**Comment by s-perron** [comment]
Thanks.  I agree the cmake feature is broken, and that is why they had to fix it.

**Comment by null77** [comment]
Can we reconsider opening this? This is affecting Chromium developers who are stuck on Python 2 for the time being. I'm trying to build SPIRV-Tools using CMake as a part of SwiftShader and am having to manually switch my environment variables.

How much work would it be to upgrade the Kokoro bots to 3.12? Or to add a workaround?

@dneto0 @dj2 fyi

**Comment by dj2** [comment]
We just had to downgrade Amber to 3.0 cmake in order to continue working with deqp. I don't think we can upgrade spirv-tools easily.
