### ISSUE TITLE
Should add_definitions(/MP4) be applied in general?

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#2620]
source/opt/CMakeLists.txt has:

if(MSVC)
  # Enable parallel builds across four cores for this lib
  add_definitions(/MP4)
endif()

I copied this when making source/reduce/CMakeLists.txt, and following me copying it again to make source/fuzz/CMakeLists.txt, @dj2 has raised the point of whether it should be applied to all of SPIRV-Tools, or just to particular libraries.

If it was only needed for opt due to that library being particularly chunky, perhaps it is not even needed for other libraries such as reduce and fuzz.

**Comment by s-perron** [comment]
It was added to make the build of spirv-tools to go faster when it is built as part of CTS.  Strictly speaking it would not be needed for components that are not part of CTS.  However, does it hurt having it for other components?  They have a benefit: faster compile times.  The cost is a few extra lines in the cmake file.

I think it is worth it.

**Comment by jeffbolznv** [comment]
Some more background on this...

MSVC supports two kinds of parallelism in its builds. By default you get parallelism between projects, with each project using one core, and building as many projects in parallel as you have cores. How well things parallelize is a function of how many dependencies you have between projects, and how well "load-balanced" your projects are. If you add /MPN to a project, then that project uses up to N cores. Beware mixing these - you can end up using N^2 cores.

The CTS build was suffering because most projects depend on the compiler toolchain, which all depends on spirv-tools + spirv-tools-shared, and those projects had slow build times. So the first half of the CTS build was only compiling these two projects and only using two cores, and taking several seconds per file. /MP4 seemed like a decent tradeoff in terms of getting a meaningful speedup, not behaving too badly if a build does have N-1 other projects building as well, and being simple.

I also added PCH to these projects, which was maybe a 3x speedup, and these speedups were additive (multiplicative?). With spirv-tools being built into so many Vulkan projects I work with on a daily basis (glslang, CTS, ValidationLayers) this was a big quality of life improvement.

IMO /MP4 is still working well for CTS and other projects, and those projects don't build any of the other spirv-tools components, so they have no bearing on whether you apply it to other components. When I've built spirv-tools recently (using MSVC), I've noticed that other components have started to dominate the build time, e.g. some test libraries have gotten rather large. They'd benefit from /MP4 (or PCH improvements), but I don't build them very frequently so I haven't bothered. But if it would benefit others, then I think it's fine to selectively apply it. But if you just apply it everywhere, then you risk using 4*N cores which might make the system unresponsive while it's building.

FWIW, none of this applies if you use ninja, and I'm under the impression a lot of people on this project use ninja. ninja behaves more like you just have a flat list of files with /MP(N+2). I could never get PCH to work with ninja so in my testing of the CTS build MSVC was faster than ninja, but that can vary a lot across projects.
