### ISSUE TITLE
Entry function inline

### ISSUE THREAD

**Issue by jaebaek** [KhronosGroup/SPIRV-Tools#2786]
This is related to https://github.com/microsoft/DirectXShaderCompiler/issues/2381.

When DXC compiles vtx_input.hlsl to vtx_input.spv.fcgl, it emits temporary variables to handle the entry function.
When we run spirv-opt to inline the entry funtion, those temporary variables still exist.
(Please check vtx_input.spv.opt for the output of spirv-opt)

[vtx_input.hlsl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3473902/vtx_input.hlsl.txt)
[vtx_input.spv.fcgl.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3473903/vtx_input.spv.fcgl.txt)
[vtx_input.spv.opt.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/3473904/vtx_input.spv.opt.txt)

**Comment by s-perron** [comment]
Scalar replacement does not replace the local struct because some of the members have a relaxed precision decoration.  This should be handled.  We also need to make sure the decoration gets passed from the member to the new variable.  Once scalar replacement does its job, the rest of the optimizations work as expected.

Also, I noticed this sequence which could be simplified to a vector shuffle:

```
         %88 = OpCompositeExtract %float %34 3
         %89 = OpCompositeExtract %float %85 0
         %90 = OpCompositeExtract %float %85 1
         %91 = OpCompositeExtract %float %85 2
         %92 = OpCompositeConstruct %v4float %89 %90 %91 %88
```

DXC would not expect DXC to do that change.  We could have a separate issue for spirv-tools, but it would be low priority.  I don't expect it would have much effect.  It could help reduce the size of the spir-v a little bit.
