### ISSUE TITLE
HLSL legalization: transform ImageOperands Offset -> ConstOffset

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/SPIRV-Tools#3005]
We got a bug report recently from a developer whose Spiregg-generated shader had the following line:

```
         %92 = OpImageFetch %v4float %91 %87 Lod|Offset %88 %90
```

This is invalid in Vulkan due to this rule in the SPIR-V environment appendix:

```
  * Image operand code:Offset must: only be used with
    code:OpImage*code:Gather instructions.
```

I don't have a source shader I can share, but I think this bug could be reproduced with a shader that does something like: `tex.Load(coord, int2(i, i))` where `i` is a loop induction variable. This could have been made legal by unrolling the loop, detecting constant offsets, and replacing Offset->ConstOffset.

Also, as far as I can tell, the validator doesn't have any code to validate this rule from the Vulkan environment.

**Comment by greg-lunarg** [comment]
Just from reading the description, I am guessing the issue is that spirv-opt cannot unroll the loop as it stands. Unrolling is called from the dxc legalization recipe, but the algorithm is not as robust as it could be and a number of  conditions prohibit unrolling that could be overcome with some additional logic in the unroller.

If this is the case, it would really help (maybe even be necessary) to have the shader in hand. LunarG does have a secure method to hand code over if that is a concern. Just let me know and we can line it up.

It could also be that legalization is not getting enabled in dxc. Legalization is not always done by dxc; detection of certain language features cause legalization to occur and the problem could be in the detection. So this could be a dxc problem.

I will try cobbling up a shader and report back on what I see.

**Comment by jeffbolznv** [comment]
The loop is unrollable, it's just a loop from 0 to a literal constant. I tried running it through spirv-opt again with --hlsl-legalize but it still didn't get unrolled. I didn't try to debug it any further than that.

I haven't gotten permission to share the developer's shader.

**Comment by greg-lunarg** [comment]
--legalize-hlsl invokes the unroller, so it seems there is some issue with the unroller.

**Comment by greg-lunarg** [comment]
Is the loop preceeded with [[unroll]]? The unroller will only unroll such loops.

**Comment by jeffbolznv** [comment]
I don't think so, at least it's not in the SPIR-V.

I'm not really familiar with what the flow is for HLSL through spiregg. Is the shader author required to decorate loops with [[unroll]] to make them legal? Or should spiregg be flagging loops that need unrolling?

Even if it had [[unroll]], I still don't see any code in spirv-opt to convert Offset->ConstOffset.

**Comment by s-perron** [comment]
We can look into the Offset->ConstOffset pass.  There is nothing that does that yet.  It could be a simple instruction folding rule.  If the image operand has "offset" and the given offset is a constant, we can change it to "const offset".

For the unrolling, it was a conscience design decision to only unroll loops that have the unroll bit set in the loop control.  This is because the ideal amount of loop unrolling is hardware dependent, and we do not want to step on the toes of the drivers.

It will take me a while before I get to this, but, if someone else wants to contribute, it would be welcome.

**Comment by jeffbolznv** [comment]
I thought there were cases where legalization had to unroll things in order to make them legal. There was even a GDC (2018?) presentation that said "Loop unrolling - Must be done for legalization". Has something changed since then? Are shader authors required to mark things as [[unroll]] in order for them to be legalized?

**Comment by s-perron** [comment]
Yes, they are required to add "[[unroll]]" for them to be unrolled in order to enable other passes to legalize the code.

**Comment by greg-lunarg** [comment]
Here is an HLSL shader that I think we can use:

```
Texture2D g_tColor ;

struct PS_OUTPUT
{
    float4 vColor : SV_Target0 ;
} ;

struct PS_INPUT
{
    int3 vTextureCoords : TEXCOORD2 ;
} ;

PS_OUTPUT MainPs ( PS_INPUT i )
{
    PS_OUTPUT ps_output ;

    float4 c = 0.0;
    [[unroll]]
    for (int ii = 0; ii < 4; ++ii) {
        c += g_tColor . Load ( i . vTextureCoords, int2(ii, ii));
    }
    ps_output . vColor = c;
    return ps_output ;
}

```

**Comment by ehsannas** [comment]
@greg-lunarg I'm wondering if you have worked on a "Offset->ConstOffset pass"?
We have a DXC issue https://github.com/microsoft/DirectXShaderCompiler/issues/2562 that boils down to having such a pass.

**Comment by ehsannas** [comment]
I've posted https://github.com/KhronosGroup/SPIRV-Tools/pull/3024 for updating "Offset->ConstOffset" if the image operand is a constant.

**Comment by greg-lunarg** [comment]
I have not started work on this. If someone wants to run with it, go for it! Thanks!
