### ISSUE TITLE
SPIR-V Questions

### ISSUE THREAD

**Issue by Keryen** [KhronosGroup/SPIRV-Tools#3018]
Dear all,

I have a few questions of SPIR-V implementation for OpenCL.

The first one is about the tool spirv-opt from the project SPIRV-TOOLS. When you use that tool like "spirv-opt test.spv -o test.spv", it changes something at the file or it does not do anything by not using any flag? I think it is like a "No action" flag but I am not 100% sure about that.

The second doubt is about C++ with OpenCL. I have seen that at a C host code, if you want to compile a SPIRV file instead of the source code, you can use createProgramWithIL. I am trying now to use something similar at C++ but I do notfind anything.

Also, i have one more question. I need SPIRV metrics to make abstractions for a project, because I am using iteratively flags for evaluating different changes, in different order, so I need to know how the code have change, and I can see that "change" with their metrics. There is something similar with the llvm opt command: the use of the flag '-analyze' gives you the metric of the bytecode used as input. I need something equivalent but for SPIRV files.

Thanks in advance!

**Comment by s-perron** [comment]
> When you use that tool like "spirv-opt test.spv -o test.spv", it changes something at the file or it does not do anything by not using any flag?

It does not do anything.  It may remove OpNop instructions, but otherwise it should be the same.

It don't know if this is the right place for the second question.  Personally, I do not know anything about C++ with OpenCL.

Sorry we do not have any type of analysis or metrics tools.  We do not have any plans for something like that in the near future.
