### ISSUE TITLE
opt: dEQP-VK.graphicsfuzz.always-false-if-in-do-while

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3030]
This test fails. To reproduce: 

```
spirv-opt -O -o temp.spv *.spv
spirv-val temp.spv
```

[always-false-if-in-do-while.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/3833312/always-false-if-in-do-while.zip)

**Comment by greg-lunarg** [comment]
Are these regressions or new tests?

**Comment by s-perron** [comment]
These are new tests.

**Comment by s-perron** [comment]
There is an if-statement where the if branch returns, and the else branch computes an address that is used in the merge.

After merge return, the address computation no longer dominates its use, so merge return has to add a phi instruction.  However, this results in a variable pointer, which is not allowed.

**Comment by dneto0** [comment]
Nice bug.

We can either move the access chain instruction, or duplicate it.  
That new access chain instruction can either be pushed up until it dominates the return (which might be impossible in some cases), or sunk into the merge block.  I bet sinking it is the better option: Block 35 dominates block 34, so any operands to the access chain in 35 would also be usable in the access chain in 34.

**Comment by dneto0** [comment]
Question is: does that dominance relationship always hold?  If strict logical addressing is in effect, then I think it does hold for the problematic case, exactly because the original pointer value %40 itself is used in that block 34. ??

That's hand-wavy, sure, but that's the direction I would pursue.

**Comment by s-perron** [comment]
I believe the correct solution is to sink the access chain.  Then instead of creating an OpPhi for the result of the access chain, we create an OpPhi for any parameters of the OpAccessChain that does not dominate it new location.  That parameter could be the address operand, which we would then need to recursively sink as well.

The "sink" operation would actually be a duplication not a move.  The result of the OpAccessChain could be used multiple times.  Some of them would still be dominated, others not.

**Comment by sugoi1** [comment]
Friendly ping. This is preventing SwiftShader from passing dEQP 1.2.1.
