### ISSUE TITLE
Incorrect OpLine handling in SPIRV-Opt

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/SPIRV-Tools#3090]
Currently SPIRV-Opt associates an OpLine with the next instruction, and only that line (https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/ir_loader.cpp#L42). 

According to the spec, the OpLine associates to:

> the instructions physically following this instruction, up to the first occurrence of any of the following: the next end of block, the next OpLine instruction, or the next OpNoLine instruction.

So, in the following the OpLine should apply to all the rest of the instructions not just the OpLoad.

e.g.:
```
     OpLine %1 2 0
%a = OpLoad %float %vColor
%b = OpFOrdLessThan %bool %a %float_0
     OpSelectionMerge %2 None
     OpBranchConditional %b %3 %4
```

**Comment by dj2** [comment]
@dneto0 is my reading of the spec correct here?

**Comment by s-perron** [comment]
You are reading the spec correctly.  However, your understanding of the ir representation is off.  When we add an OpLine instruction to the debug line instructions for a given instruction, it does not mean that it applies only to that instruction.  To see that, notice what happens when we are regenerating the spir-v binary.  We will regenerate the exact same code that you started with.  We will not generate an OpNoLine before the OpFOrdLessThan, so the OpLine will still apply to it.

This has problems for optimizations.  If we delete the OpLoad, we delete the OpLine as well, and the debug information is lost.  That is why we added the two passes: propagate-line-info and eliminate-redundant-line-info.  The first will create a copy of the OpLine instructions for each instruction to which they apply, which seems to be what you want.  The second will removes OpLine instruction that would be redundant.  This way the final spir-v will not be bloated with useless OpLine instructions.
