### ISSUE TITLE
Improve MergeReturn to not add loop when function does not contain one

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#3127]
Currently MergeReturn adds a loop to the function. This can be disadvantageous for loops containing such (inlined) functions since LoopUnrolling will not unroll loops which contain inner loops. 

Propose that the MergeReturn algorithm be improved so that it does not add a loop to functions which do not already contain a loop.

**Comment by greg-lunarg** [comment]
I would like this issue to be assigned to me.

I will probably start by just improving for functions which do not contain OpSwitch. I will add OpSwitch support after.

The basic approach is as follows:

Add logic to MergeReturn so that the new logic is only executed if the function has early returns and no loops.

Add a "returned" boolean variable to the function that keeps track if the function has returned. It is initialized to false. Also add a variable to keep track of the return value if the function is not void. 

Replace all OpReturn* with code which sets the "returned" boolean to true and saves the return value if present. If the OpReturn* is contained in a selection construct, add a branch to its merge block. Otherwise add a branch to the OpFunctionEnd.

For all selection constructs originally containing an OpReturn, replace its merge block with code which checks the boolean for true and if so, branches around all code from the original merge block to the merge block of the next containing selection construct, or to the OpFunctionEnd if no containing selection construct.

Finally, before the OpFunctionEnd, insert a new OpReturn, or OpReturnValue of the return value if needed.

**Comment by greg-lunarg** [comment]
The new logic will generate OpLoads and OpStores to the new variables.

**Comment by greg-lunarg** [comment]
For example, given:

static const int eBlendNone = 0;

static float4 BlendValue(float4 base) {
    if(blend == eBlendNone)
        return base;
    return float4(0, 0, 0, 1);
}

generate:

static float4 BlendValue(float4 base) {
    bool retd = false;
    float4 retval;
    if(blend == eBlendNone) {
        retd = true;
        retval = base;
    }
    if (!retd) {
        retval = float4(0, 0, 0, 1);
    }
    return retval;
}

**Comment by s-perron** [comment]
Most of what you described is already implemented.  We already create two new symbols.  One is the boolean the says whether or not we have already hit a return (see [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/merge_return_pass.cpp#L549)).    The same for the return value (see [here](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/merge_return_pass.cpp#L522)).

The original implementation of merge return did just what you are suggesting.  We moved away from it because it creates a lot of extra cases.  The assumption "We are always in a loop and can break to the merge of the loop" made the code much simpler.  If you look at the history of merge return, you will see that there were many bugs.  It is very hard to get all of the cases, especially making sure all of the OpPhi instructions that need to be generated are generated.

If you want to do this, you will have to be very careful, and know that you will probably get many bugs that will need to be fixed asap.  Before you do it, I also want you to suggest alternatives.  It might be less error prone to fix loop unrolling to handle non inner most loops.  It would also be more generally useful.

Another solution might be to look into using a dummy switch instead of a loop in merge return.  I could not use the switch earlier because at that time the spec did not allow breaking out of a selection construct to break of a switch.  Now it does.  That might be a good option as well.

**Comment by greg-lunarg** [comment]
Thanks for the very useful feedback.

I can believe that dealing with OpPhi's could be very tricky. My plan was to only support very raw SPIR-V, much as it comes straight from the frontend, where any values carried between blocks is done through variables. Since merge-return generally is called very early (its original purpose was to aid inlining), this would not be too restrictive. I would have to add some additional checking for that in case someone tried to invoke it on more optimized code.

I did consider trying to improve loop unrolling as well. Improving merge-return seemed slightly simpler and slightly less risky.

Your dummy switch idea is more intriguing, however. It is much simpler and it solves the problem I was seeing. I will push ahead with that.

**Comment by greg-lunarg** [comment]
@s-perron Which wording in the SPIR-V spec now allows branches to the innermost enclosing switch's merge block? I am not seeing it in 1.5 Rev 2, Unified, section 2.1 (Structured Control Flow).

**Comment by s-perron** [comment]
@alan-baker Can you answer Greg's question?

**Comment by alan-baker** [comment]
@greg-lunarg Refer to Khronos SPIR internal merge request 164. It will be published with the next revision of the spec.

**Comment by greg-lunarg** [comment]
I am presuming then that code utilizing OpSwitch will need to be predicated on the user targeting spirv1.5 and above and the previous code adding a loop will need to remain when targeting anything less.

**Comment by greg-lunarg** [comment]
@alan-baker It appears that it is valid to "break" from the innermost loop even when the "break block" is nested in a case construct which is nested in the innermost loop. Can you confirm?

**Comment by alan-baker** [comment]
>I am presuming then that code utilizing OpSwitch will need to be predicated on the user targeting spirv1.5 and above and the previous code adding a loop will need to remain when targeting anything less.

No, this should not depend SPIR-V 1.5. The spec change is considered a bug fix.

> It appears that it is valid to "break" from the innermost loop even when the "break block" is nested in a case construct which is nested in the innermost loop. Can you confirm?

Yes, currently you can always break out of the innermost loop.

**Comment by jekstrand** [comment]
> Currently MergeReturn adds a loop to the function. This can be disadvantageous for loops containing such (inlined) functions since LoopUnrolling will not unroll loops which contain inner loops.

Drive-by comment:  SPIRV-opt should probably unroll all loops that have exactly zero or one iterations regardless of what's inside the loop.  `do { /* stuff */ } while(0);` has been the standard way to write multi-line macros in C for decades.  Some compilers allow statement expressions these days but the old do-while trick is still in very common use.  Given how ubiquitous it is in C, it's likely also used in shaders.  In fact, I'm pretty sure we've seen it in the wild because our compiler stack has explicit handling for it in our loop unrolling code. :smile_cat:
