### ISSUE TITLE
Make spvOpcodeString() part of the public API

### ISSUE THREAD

**Issue by c0d1f1ed** [KhronosGroup/SPIRV-Tools#3138]
In https://swiftshader-review.googlesource.com/c/SwiftShader/+/38820 we added a forward declaration of spvOpcodeString() to our code base. Adding it to the public API of SPIRV-Tools would allow it to be used more widely and help avoid breakage.

**Comment by dneto0** [comment]
Sending to @s-perron 

This API and its implementation is stateless (doesn't need a spv_context), so we can expose this 
with little work.   The comment on the method has to say that it assumes the opcode is valid, based on the spirv.core.grammar.json used when building SPIRV-Tools.  (At the moment it otherwise asserts out in a debug build.)
