### ISSUE TITLE
Wrap OpKill is not wrapping functions calling kills in single block loops

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/SPIRV-Tools#3264]
Reduced from a graphicsfuzz testcase.

```
OpCapability Shader
OpCapability Linkage
OpMemoryModel Logical GLSL450
%void = OpTypeVoid
%bool = OpTypeBool
%undef = OpUndef %bool
%void_fn = OpTypeFunction %void
%main = OpFunction %void None %void_fn
%main_entry = OpLabel
OpBranch %loop
%loop = OpLabel
%call = OpFunctionCall %void %sub
OpLoopMerge %exit %loop None
OpBranchConditional %undef %loop %exit
%exit = OpLabel
OpReturn
OpFunctionEnd
%sub = OpFunction %void None %void_fn
%sub_entry = OpLabel
OpSelectionMerge %ret None
OpBranchConditional %undef %kill %ret
%kill = OpLabel
OpKill
%ret = OpLabel
OpReturn
OpFunctionEnd
```

Running --wrap-opkill on the above input produces no change, but the `%sub` is called from the continue construct.

**Comment by greg-lunarg** [comment]
A thought: this loop (and really any single block loop containing a call) could be rewritten such that the call is not in the continue construct. Not only does this suggest a possible solution, but suggests to me that this might not really be a problem at all.

Going to look at #2433 to better understand the problem we are trying to solve.

**Comment by greg-lunarg** [comment]
It still is a problem based on the rule that the back-edge block must post-dominate the continue target.

Rewriting the loop has a size cost as well since it introduces a branch and label per loop, whereas wrapping an opkill only has a cost per module.

The best solution here is probably just to fix the algorithm that recognizes function calls in continues, since I am guessing that is where the problem lies.
