### ISSUE TITLE
spirv-fuzz: transformation to add Relaxed to live safe functions and dead blocks

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/SPIRV-Tools#3502]

**Comment by afd** [comment]
@antnkarp This would be a good one for you to take - and of course we will provide some actual text about the issue :)  Please reply and then we can assign you.

**Comment by antnkarp** [comment]
That's great. Thanks a lot.

**Comment by afd** [comment]
SPIR-V has a Relaxed decoration that can be applied to result ids of certain types to say that they can be computed with relaxed precision (i.e., using fewer bits than normal).

spirv-fuzz needs to preserve the semantics of a SPIR-V module so it cannot add Relaxed to any old id.

However, if an id is in a *dead* block - a block that has been added by spirv-fuzz but that is guaranteed to be unreachable at runtime - then it is fine to decorate this id with Relaxed.

This issue involved:

- Adding a new transformation - TransformationAddRelaxedDecoration - to spirv-fuzz.  This should take as an argument the id of an instruction and, to be applicable, should require that the instruction is in a dead block and that the instruction's result type is something to which Relaxed can be applied.  When applied it should add the relaxed decoration to the id.

- Adding a new fuzzer pass - FuzzerPassAddRelaxedDecorations - that runs as one of the final passes applied by spirv-fuzz.  This should - with some probability - add Relaxed to any relevant id.

Some notes for @paulthomson and @Vasniktel for info: I think it might be good - once we have it - to extend this so that Relaxed can be applied to any id that has the arbitrary value fact.  That should be an easy change to make later, so I think @antnkarp should go ahead and work on this transformation as described above for now.

**Comment by paulthomson** [comment]
Guide to writing a spirv-fuzz fuzzer pass:

https://github.com/KhronosGroup/SPIRV-Tools/blob/master/docs/spirv-fuzz.md
