### ISSUE TITLE
spirv-fuzz: Invalidation when indexing into a structure

### ISSUE THREAD

**Issue by andreperezmaselco** [KhronosGroup/SPIRV-Tools#3671]
`spirv-val` invalidated a fuzzed shader because the result id of an `OpConstantNull` instruction was being used to index into a structure. According to SPIR-V specification, when indexing into a structure, each index must be the result id of an `OpConstant` instruction.
```
error: line 79: The <id> passed to OpInBoundsAccessChain to index into a structure must be an OpConstant.
  %399 = OpConstantNull %uint
```
Debugging `spirv-fuzz`, I found that `TransformationReplaceIdWithSynonym` checks only if the index instruction is `OpAccessChain`, while the same is true for `OpInBoundsAccessChain` and `OpPtrAccessChain`.

**Comment by paulthomson** [comment]
`TransformationReplaceIdWithSynonym` is careful to avoid replacing id uses that index into a struct with synonyms because the indices can only be `OpConstant` instructions. However, the check only considered `OpAccessChain` instructions, even though the same restriction applies to `OpInBoundsAccessChain`, `OpPtrAccessChain`, etc.
