### ISSUE TITLE
spirv-fuzz: Transformation to replace id in OpPhi when predecessor is dead

### ISSUE THREAD

**Issue by stefanomil** [KhronosGroup/SPIRV-Tools#3726]
The transformation to add an OpPhi synonym (issue: #3592 , PR: #3701 )
accepts a mapping from the predecessors of a block to ids that must
all be synonymous. If an id corresponds to a predecessor that is a
dead block (it will never be executed), this rule can be relaxed and
we could accept any available id of the right type.

After the discussion: we could actually make a new transformation for
replacing ids in OpPhi instructions.

**Comment by Vasniktel** [comment]
Maybe we can make a separate transformation that checks if the id belongs to a dead block and replaces it with any other id in that case.

Or, maybe it is better to mark an id as irrelevant if it belongs to a dead block. I guess we can't mark it as irrelevant if the id is a pointer. But in that case, `OpPhi` can't take pointer operands without `VariablePointers` capability.

@stefanomil, @afd, @paulthomson, what do you think?

**Comment by stefanomil** [comment]
I think that we also want to be able to use any id of the right type (even if it does not belong to a dead block), as long as it is paired with a dead predecessor.

For example, if we have (in pseudocode):

%1 = 1
if (true) {
[Label: 10]
 %3 = 2
} else {
[Label: 11]
 DEAD
}

then we could add
%id = OpPhi %type %1 %10 %3 %11
because block %11 is dead, so the value %3 should never be chosen.


Maybe we could have a transformation that takes an OpPhi which is synonymous with all the values that it can take and it replaces some of the ids with other ones of the right type but not necessarily synonym, if they correspond to dead predecessors

**Comment by Vasniktel** [comment]
I don't think %3 is available in the merge block in your example.

**Comment by Vasniktel** [comment]
I might be missing something but I think IdIsIrrelevant should work here. Could you elaborate a bit more on your example?

**Comment by stefanomil** [comment]
Yes, sorry, I put the ids in the wrong positions.

If you look at the example now, %1 might not be irrelevant but it could still be used in the OpPhi because block 11 is dead. More in general, if we have

```
%id = OpPhi %type %id_1 %pred_1 ... %id_n %pred_n
```
where %id, %id_1, ..., %id_2 are all synonyms, and we have, for example, %id_other available to use here, with the right type but not synonym with the other, we should be able to replace %id_k with %id_other if %pred_k is dead, regardless of which block %id_k belongs to.

**Comment by Vasniktel** [comment]
I think your transformation on replacing irrelevant ids would be able to replace %id_k with %id_other if we mark %id_k as irrelevant, wouldn't it?

**Comment by stefanomil** [comment]
Yes, but we are not sure that %id_k can be marked is irrelevant (maybe it is used later on)

**Comment by Vasniktel** [comment]
Yes, you are right. Haven't thought about that.

**Comment by stefanomil** [comment]
Now that I think about it, we can just have a transformation that takes:
- the id of a OpPhi instruction
- the label id of a predecessor
- an id of the right type that is available at the end of the predecessor

and it just replaces the id associated in the OpPhi with the one given, and it is applicable if the predecessor is dead, and the predecessor is actually a predecessor of the block where the OpPhi instruction is located

**Comment by Vasniktel** [comment]
From the updated coment:
> However, would it matter if the block is dead? %id_k should never be executed. Does this mean that we can mark all instructions in dead blocks as irrelevant? This requires some thought.

@stefanomil, what do you think?

**Comment by Vasniktel** [comment]
That being said, for block A and its successor B, if A is dead and:
1. A dominates B - B is dead as well
2. A does not dominate B - the only users of ids from A can be OpPhis in B

This requires some thought, though.

**Comment by stefanomil** [comment]
> From the updated comment:
> 
> > However, would it matter if the block is dead? %id_k should never be executed. Does this mean that we can mark all instructions in dead blocks as irrelevant? This requires some thought.
> 
> @stefanomil, what do you think?

**However, would it matter if the block is dead?**
Yes, because %id_k could be in some non-dead ancestor of the dead block

I think that we could mark all the instructions in dead blocks as irrelevant, but it's not necessarily related to this issue

**Comment by Vasniktel** [comment]
Yes, you are completely right! Sorry for the confusion.

> Now that I think about it, we can just have a transformation that takes:
> 1. the id of a OpPhi instruction
> 2. the label id of a predecessor
> 3. an id of the right type that is available at the end of the predecessor
> 
> and it replaces the id associated in the OpPhi with the one given, and it is applicable if the predecessor is dead, and the predecessor is actually a predecessor of the block where the OpPhi instruction is located

Sounds like a good idea.

**Comment by stefanomil** [comment]
@afd @paulthomson Could you read this proposal and make observations, ask for clarification or assign this issue to me?

> Now that I think about it, we can just have a transformation that takes:
> 
> * the id of a OpPhi instruction
> * the label id of a predecessor
> * an id of the right type that is available at the end of the predecessor
> 
> and it replaces the id associated in the OpPhi with the one given, and it is applicable if the predecessor is dead, and the predecessor is actually a predecessor of the block where the OpPhi instruction is located

**Comment by afd** [comment]
Thanks for the discussion!  I agree with @Vasniktel that we could probably mark all ids defined in dead blocks as being irrelevant.  But indeed that's separate from this issue.  @Vasniktel could you please open an issue for that, so that we can discuss it a bit?

Regarding this issue, @stefanomil I think what you are proposing is:

(1) Keeping the transformation that creates synonyms via OpPhi instructions as it is
(2) Adding a new transformation + fuzzer pass that can change the value consumed by an OpPhi for a dead predecessor

i.e. decouple the two concepts.

I think that this is the right way to go.

I went through this thought process to come to that conclusion:

Suppose we have this scenario:

```
  A
 / \
C   D(dead)
 \ /
  B
```

Let's say that C generates an id %foo and D generates and id %bar, and they have the same type but are *not* synonymous.

If we don't have *any* synonyms for %foo then a disadvantage of what you're proposing would be that we would not make a %foo synonym in B via an OpPhi that consumes %foo and something else, because no synonyms for %foo are available in D.

However, in that case it might not be very useful to have a %foo synonym at B, because %foo won't be used after C (unless in an OpPhi at the start of C).


And e.g. A generated %baz such that %foo and %baz are synonyms, we could add an OpPhi at B that consumes %foo from C and %baz from D, and then later we could change the consumption of %baz to a consumption of %bar.
