### ISSUE TITLE
spirv-fuzz: All instructions in a dead block are irrelevant

### ISSUE THREAD

**Issue by Vasniktel** [KhronosGroup/SPIRV-Tools#3733]
Consider marking all instructions in dead blocks as irrelevant.

**Comment by afd** [comment]
@stefanomil Let's discuss this when you're ready to work on it.

**Comment by stefanomil** [comment]
I can think of two approaches for this:

(1)
Change the IdIsIrrelevant and GetIrrelevantIds functions, so that, in addition to checking the irrelevant_ids_ set, they also consider irrelevant any instruction that is in a dead block. (This will require adding the context to the parameters of these functions)

Pro: any new instructions added to a dead block will always be considered irrelevant
Con: GetIrrelevantIds cannot just return a const reference to the set of irrelevant ids anymore, but it will need to copy it and add any additional ids from dead blocks

(2)
Change the AddFactBlockIsDead, so that it adds an IrrelevantId fact for each id in the block. (This will require adding the context to the parameters of this function)

Pro?: if instructions are moved out of the block, they will still be considered irrelevant (I'm not sure if this is actually desirable, though)

**Comment by afd** [comment]
I think option (1) is good.

I think we *would* like instructions that get migrated out of dead blocks to be considered irrelevant, but we could handle that by checking for it and adding explicit IrrelevantId facts when such movement happens.

@Vasniktel what do you think?  Some of your transformations move instructions around.

**Comment by Vasniktel** [comment]
I'm OK with (1). Regarding the need for the IR context as an argument, I'm going to refactor the fact manager take this into account.
