### ISSUE TITLE
spirv-opt: How to include "GLSL.std.450" instruction set in optimization pass

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/SPIRV-Tools#4094]
Hi all,

Since a recent update (Dev. 2020) of SPIRV-Tools, our custom optimization pass to fuse multipl-add intrstructions doesn't work properly anymore.
There seems to be a new way to include the instruction set `GLSL.std.450` in a sub-class of `Pass` when it had not been included yet.
I adopted this from `amd_ext_to_khr.cpp` and the beginning of the `Process()` function looks like this:
```cpp
  uint32_t inst_set_id = ctx->get_feature_mgr()->GetExtInstImportId_GLSLstd450();
  if (inst_set_id == 0) {
    ctx->AddExtInstImport("GLSL.std.450");
    inst_set_id = ctx->get_feature_mgr()->GetExtInstImportId_GLSLstd450();
    status = Status::SuccessWithChange;
  }
```
However, this triggers the assertion `"An analysis in the context is out of date."` in `Pass::Run()` because `ctx->IsConsistent()` returns false now.

Cany anyone tell me what is the proper way to include this instruction set if the SPIR-V module doesn't include it before the optimization pass runs?

**Comment by s-perron** [comment]
The code snippet you provided looks correct.  I'm not sure what the problem is.  

Do you know which analysis is failing the consistency check?  Sorry I cannot help you out more without being able to run something myself.  This should probably be refactored to add more detailed information.  See where IRContext::IsConsistent return false.  Then we need to see what is different in the failing analysis.
