### ISSUE TITLE
Make a CFG structurization tool

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/SPIRV-Tools#4099]
It's not the responsibility of the compiler frontend to do structurization. I don't want to do it. I've been trying for six months and cannot get it right. You must provide a tool for this. There has been talk of more prescriptive docs for this topic, but they never come. This thing is a big defect in the IR and it has to be addressed some way so that people have a fighting chance a generating validated code.

**Comment by dneto0** [comment]
SPIR-V makes promises about retaining / recovering control flow uniformity when structuring information is present:

> If control flow is uniform upon entry into a structured loop or selection, and all invocations leave that loop or selection via the header block’s declared merge block, then control flow reconverges to be uniform at that merge block.

The structuring information captures programmer intent.  We can't perfectly reconstruct it from thin air, which is why it's explicitly represented in the IR. If such a structurizer were to be written, it would have to have edge cases which cause it to fail with "I don't know what the programmer meant", or to go ahead and change program semantics.

I expect you're using LLVM, like many others, because it's such a rich set of functionality.  I completely agree; I've done so myself.
However, LLVM's heritage is as a CPU compiler which does not need to track uniformity through its optimizations.
There is ongoing work to try to add some fundamental functionality. See the `convergent` [function property](https://llvm.org/docs/LangRef.html#function-attributes).  However, even that is not settled science. See the Fall LLVM 2020  presentation: [N. Hähnle “Evolving convergent: Lessons from Control Flow in AMDGPU”](https://www.youtube.com/watch?v=_Z5DuiVCFAw)

Still, you have a practical problem.   I've seen two strategies:
- Avoid LLVM IR and its optimizations entirely:  The DXC SPIR-V backend goes from the Clang AST directly into structured SPIR-V, and then transforms using spirv-opt only, which knows how to work with structured CFGs.
- Use LLVM IR but be very careful about what transforms are used, so that structure-changing transforms don't damage semantics. As I understand it, most GPU backends do this.  A public example is Clspv.   Going down this path requires constant vigilance when you absorb updates from the upstream LLVM project.


The closest thing I've got for a restructurizer is the Tint code for transforming a structured SPIR-V CFG into a WSGL AST.  There are extensive comments and working code, starting at: https://dawn.googlesource.com/tint/+/refs/heads/main/src/reader/spirv/function.cc#77 
There are extensive tests at https://dawn.googlesource.com/tint/+/refs/heads/main/src/reader/spirv/function_cfg_test.cc

**Comment by seanbaxter** [comment]
I'm not using LLVM. I'm building SPIR-V manually. I fix one structurization bug and it causes a different one to show up. The language in the spec is not comprehensible to me. 

A challenge is that I'm emitting single-return instruction CFG, because I am supporting destructors, and I just want to emit the destructor body once for each object. It makes CFG construction more difficult, and I still get surprised by bugs. There's no IR builder included to help hold your hand through this. 

This is especially aggravating because the devices I care about, desktop GPUs, don't need this structurization. PTX doesn't have it.. The Mesa Intel drivers just convert SPIR-V to LLVM and use LLVM optimizations, so that loses structurization.

**Comment by dneto0** [comment]
Ok, it's interesting that you're not using LLVM.  That's the root cause of most complaints I hear about structurization.

The spirv-opt inliner has to convert code so it's essentially single-return.  (The inlined function may have multiple returns, but once inlined it must not.)  spirv-opt has a merge-return pass that you might learn from.

The case of supporting automatic single-copy destruction might be more specialized (and hence be supportable with less work).  I haven't thought about it, and it seems to me its codegen would have meaningful tradeoffs.

**Comment by s-perron** [comment]
We cannot write a pass that will generate correct structured control flow. As @dneto0 pointed out, your problem is essentially the same as what is done in the merge return pass. You can follow that algorithm to merge all of the returns. If you do not have any ssa values that are live across basic block boundaries, it becomes much simpler.
