### ISSUE TITLE
Vectorization for OpenCL-flavored spirv

### ISSUE THREAD

**Issue by poyaoc97** [KhronosGroup/SPIRV-Tools#4130]
Hi, I'm wondering is it feasible to add a vectorization optimization pass?
Looking for some input on spirv vectorization.

**Comment by s-perron** [comment]
That is not something the maintainers would be interested in writing ourselves.  However, we might be open to something like that if one else were to contribute it.

We have not considered doing something like that because it is common for developers to vectorize their own code.  Also, depending on which architecture the SPIR-V will be run on, vectorizing the code does not make a difference in performance because there are no intra-thread vector operations like an add instruction that adds 4 registers to 4 other registers in the same thread.  The GPUs will do SIMD across threads: there will be 32 separate instances of the kernel running.  Each instance will add 1 register to an other, so you get 32 adds done concurrently.  No vectorization is needed.  So we would want an explanation on why this would be beneficial.

The other questions would be what type of vectorization would be required?  Are we talking about merging multiple instruction in the same basic block, or do you want a loop to be unrolled and vectorized?  In either case, this code will have to use the dependence analysis that was written, but not used very much.

Let me know if I have other questions.

**Comment by s-perron** [comment]
Closing. We are going planning on this at any time. As stated above. If someone else wants to contribute the change we will accept it.
