### ISSUE TITLE
spirv-link: Generating invalid OpEntryPoint

### ISSUE THREAD

**Issue by cmarcelo** [KhronosGroup/SPIRV-Tools#4135]
Using the inputs

a.spvasm
```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "foo"
%int = OpTypeInt 32 0
%ptr_wg_int = OpTypePointer Workgroup %int
%int_0 = OpConstant %int 0
%wg = OpVariable %ptr_wg_int Workgroup
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%3 = OpFunction %1 None %2
%4 = OpLabel
OpStore %wg %int_0
OpReturn
OpFunctionEnd
```

and 

b.spvasm
```
OpCapability Shader
OpMemoryModel Logical GLSL450
OpEntryPoint GLCompute %3 "bar"
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%3 = OpFunction %1 None %2
%4 = OpLabel
OpReturn
OpFunctionEnd
```

and compiling them with (note the versions 1.0 and 1.5)

```
spirv-as --target-env spv1.0 -o a.spv a.spvasm
spirv-as --target-env spv1.5 -o b.spv b.spvasm
```

(Both validate correctly.)  Then linking with

```
spirv-link --target-env spv1.5 -o linked.spv a.spv b.spv
```

generates a file that disassambles to

```
 SPIR-V
; Version: 1.5
; Generator: Khronos; 17
; Bound: 11
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %1 "foo"
               OpEntryPoint GLCompute %2 "bar"
               OpModuleProcessed "Linked by SPIR-V Tools Linker"
       %uint = OpTypeInt 32 0
%_ptr_Workgroup_uint = OpTypePointer Workgroup %uint
     %uint_0 = OpConstant %uint 0
          %6 = OpVariable %_ptr_Workgroup_uint Workgroup
       %void = OpTypeVoid
          %8 = OpTypeFunction %void
          %1 = OpFunction %void None %8
          %9 = OpLabel
               OpStore %6 %uint_0
               OpReturn
               OpFunctionEnd
          %2 = OpFunction %void None %8
         %10 = OpLabel
               OpReturn
               OpFunctionEnd
```

but fails to validate

```
error: line 9: Interface variable id <6> is used by entry point 'foo' id <1>, but is not listed as an interface
  %6 = OpVariable %_ptr_Workgroup_uint Workgroup
```

Two potential issues:

(a) Is it valid to take 1.0 and 1.5 SPIR-V as inputs and generate a 1.5 output? If so, the linker must update the OpEntryPoint for foo to adhere to a new requirement (from 1.4) that all non-Function variables are part of the interface list.

(b) Changing b.spvasm to be compiled with 1.0 (i.e. having both inputs as 1.0) doesn't produce a SPIR-V 1.5 even when explicitly passing the `--target-env` above. Is this expected?

Note that it could be the case that linker is not expected to be able to mix SPIR-V from different versions or translate inputs from one version to another. If so, would be good if it did error or at least gave a warning on the output.

**Comment by pierremoreau** [comment]
The linker currently sets the linked module to use for version the max version of all inputs. This was mostly a placeholder (see [this current to-do](https://github.com/KhronosGroup/SPIRV-Tools/blob/c91a25af13e112729be7272d58b0df25e772c3e0/source/link/linker.cpp#L89-L91)) until a better solution was found, and at a time where deprecation had not been introduced yet in SPIR-V for example.

a) AFAICS, it should be valid to upgrade a 1.0 module to 1.5 as long as the `OpEntryPoint` is updated to the new requirements, and that the 1.0 module does not use features that were deprecated and then removed.

b) Since the output version is currently computed as the max of the input versions, it is expected that linking to 1.0 modules will output you a 1.0 module; the `--target-env` flag is only used to initialise the `IRContext` used internally by SPIRV-Tools and would typically be used during validation. The flag’s old description was “Use validation rules from the specified environment.” which was a bit misleading since no validation was actually performed, but did not set any expectation on it influencing the version of the produced linked module.

Overall I would say that the linker is able to mix different SPIR-V versions as long as each individual input module remains valid for a different SPIR-V version without needing any changes, but it should probably output a warning about the support being incomplete. If there is a SPIR-V upgrader/downgrader in SPIRV-Tools, I could try plugging it in but I do not have the time at the moment to implement such an upgrader/downgrader myself.

The following changes should be worth doing until a better solution is found:

1. Error out if the input modules use different SPIR-V versions.
2. Add an option for forcing linking even when inputs use different versions, and the value of that option would specify the version used by the linked module. In addition to that there would be a warning informing the user that the resulting binary might be invalid.

What do you think about this proposed intermediate solution, and how mixed input versions should be handled in an ideal case?

**Comment by cmarcelo** [comment]
Thanks for the answer.

I think (1) sounds fine.

For (2) I'm not familiar enough with the current usage to say how useful this option would be in practice -- what other tools are expected to consume invalid SPIR-V? If (2) exists I agree with having a warning about the result binary.

The `target-env` flag is a bit confusing: maybe the client API (vulkan, opencl, opengl, universal) is the only part relevant at the moment -- assuming the (1) behavior?

**Comment by pierremoreau** [comment]
(2) could be useful if you want to link two SPIR-V modules that uses different versions (let's say 1.0 and 1.2) and you know that the 1.0 one could be a valid 1.2 module without any tweaks (but for some reason you can not update that 1.0 to 1.2 maybe a SPIR-V binary provided by someone else?). It is more of an unlikely edge case, I agree.

An `spv_env` is required for constructing the internal `IRContext`, though it does not seem to actually be used for anything there. It could probably be removed and just use the default value of (universal) 1.5.

**Comment by pierremoreau** [comment]
Hello Caio Marcelo, sorry for dropping the ball on this one.

I have made the following changes locally and am planning on submitting them once we agree:

* When trying to link modules using different SPIR-V versions, the linker will proceed as usual but will now print the following warning:
  ```
  warning: 0: The modules given to link use different SPIR-V versions:
         1.1 1.3 1.5 (in input order)
  The highest version among them (1.5) will be used for the linked module, which might result in invalid SPIR-V.
  ```

* When printing the help message for the linker tool, this is the updated description for `--target-env`:
  ```
  --target-env <env>
               Set the environment used for loading the inputs. Without this
               flag the environment defaults to spv1.5. <env> must be one of
               {vulkan1.1spv1.4|vulkan1.0|vulkan1.1|vulkan1.2|spv1.0|spv1.1
                |spv1.2|spv1.3|spv1.4|spv1.5|opencl1.2embedded|opencl1.2
                |opencl2.0embedded|opencl2.0|opencl2.1embedded|opencl2.1
                |opencl2.2embedded|opencl2.2|opengl4.0|opengl4.1|opengl4.2
                |opengl4.3|opengl4.5}.
               NOTE: This has no impact on the SPIR-V version used by the
               linked binary module, nor the version used in each input.
  ```

**Comment by pierremoreau** [comment]
@airlied How do you think it should work in clover when linking against libclc? At the moment only SPIR-V 1.0 is supported, but if support for 1.5 (for example) was added, should it continue to link against the 1.0 spirv64-mesa3d-.spv or would a 1.5 version be needed? A new version will be needed if new built-ins are added, in which case should the old version be kept around for when the user sends in 1.0 binaries?

I am re-spinning the patches mentioned in the previous comment, and initially decided to go with emitting an error in case of version mismatch as I came to agree with @cmarcelo that it was unlikely to happen, but then I remembered clover is linking against libclc which has a fixed SPIR-V version that might differ from what the user provides..

**Comment by airlied** [comment]
@pierremoreau we only link to libclc using NIR we never link the SPIR-V with the user supplied SPIR-V.

**Comment by pierremoreau** [comment]
Ah okay, thank you for the clarification!

**Comment by djdeath** [comment]
Looks like this change did not add the (2) option which would allow to force linking modules of different version.

I'm trying to deal with that case with SPIRV-LLVM-Translator (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1445).

Unfortunately the user of that project cannot set a particular version for the translator to generate with. Only a range from [1.0, 1.X]. And the translator will pick the lowest version based on features used.
