### ISSUE TITLE
spirv-fuzz: Permute the order of variables at function scope

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4194]
The order in which variables are declared in a function should not matter. The order in which global variables (and more generally global declarations) appears doesn't matter as long as def-use constraints are satisfied. There is scope for both kinds of permutation.

@dneto0 thanks for suggesting this.

@Vasniktel does the transformation for moving an instruction within its block already take care of OpVariable instructions?

**Comment by Vasniktel** [comment]
No, we don't support `OpVariable` in that transformation. We could extend it but that might not be a good idea since most of the code in that transformation is concerned with swapping memory-related instructions correctly (e.g. swapping two `OpStore`'s) and swapping `OpVariable`'s wouldn't fit the current implementation (since there are no constraints for their ordering). I think it's better to have a separate transformation for this (in the same way we have a transformation that permutes function parameters).

**Comment by afd** [comment]
Here's a description of the issue for someone wishing to solve it.

The first block in a function starts with 0 or more OpVariable instructions. The order in which these instructions appear should not matter, thus they can be permuted.

It would make sense to implement a new transformation, `TransformationSwapFunctionVariables`, that takes the ids of two variables, checks that they exist and are in the same function (in `IsApplicable`), and swaps them (in `Apply`).

Then a new fuzzer pass, `FuzzerPassPermuteFunctionVariables` could randomly permute the variables of functions in a module by applying random swaps.

This fuzzer pass should be a "final" fuzzer pass in `fuzzer.cpp`.
