### ISSUE TITLE
spirv-fuzz: Introduce vector operations

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4195]
If we have an operation like c = a + b, where a, b and c are scalars, then we could turn this into:

va = vector(..., a, ...);
vb = vector(..., b, ...);
vc = va + vb;
c = vc[appropriate component];

The missing components of va and vb could be populated using arbitrary instructions, or using OpUndef, as long as it is acceptable to perform the operation on undefs / for all possible values (e.g. this might be a problem for division).

Instead of replacing the computation of c we could add a synonym between c and vc[appropriate component].

There would also be scope for:

- embedding a and b in larger vectors if they are already vectors
- applying this to longer sequences of arithmetic operations

@dneto0 Thanks for the suggestion that led to this issue.

**Comment by Vasniktel** [comment]
One way of implementing it would be to have a set of supported operands (e.g. `OpIAdd` and others from https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_arithmetic_a_arithmetic_instructions). Then, we can transform the following code:
```
%1 = OpIAdd %uint %a %b
```
into
```
%2 = OpCompositeConstruct %uvec3 %uint_1 %a %uint_1
%3 = OpCompositeConstruct %uvec3 %uint_1 %b %uint_1
%4 = OpIAdd %uvec3 %2 %3
%a = OpIAdd %uint %a %b
```
We can then say that `%2[1]` is synonymous with `%a` and `%3[1]` is synonymous with `%b`.

Points to take into account:
- `OpIAdd` and similar instructions support vector operands. In that case, we can embed those operands into bigger vectors if possible (i.e. if `%1`'s operands are `%uvec4` then we can't embed it anywhere since the maximum size of a vector is 4).
- We can probabilistically select the position in the vector where we want to embed the component into.
- Some care must be taken with regards to the `%uint_1` constants above. We must make sure that we don't introduce undefined behaviour. For example, divide by 0 or [OpSDiv UB](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpSDiv). Thus, we should be careful when we decide if we want to mark the constant `%uint_1` as irrelevant.

**Comment by afd** [comment]
Notes from a chat with @Vasniktel about this:

We have a new transformation T(fresh, existing, v1, v2, index):
	- fresh is a fresh id
	- existing is an instruction of the form "c = a OP b"
	- v1 is a composite such that v1[index] is synonymous with a
	- v2 is a composite such that v2[index] is synonymous with b
	- v1 and v2 are available at existing

Effect:
	- Adds instruction "fresh = v1 OP v2" after existing
	- Adds a synonym: existing = fresh[index]

The fuzzer pass can take care of identifying the c = a OP b and preparing the composites.
