### ISSUE TITLE
Piecewise copy of matrix is poorly optimized

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/SPIRV-Tools#4371]
Modifying individual elements of a matrix results in extraneous matrix copies that are not optimized away.

For example:

```
void main() {
    mat4 mat = frameUniforms.clipFromWorldMatrix;
    mat4 rot;

    rot[0][0] = mat[0][0];
    rot[0][1] = mat[0][1];
    rot[0][2] = mat[0][2];
    rot[0][3] = mat[0][3];
    ...
}
```

Results in:

```
    mat4 _89 = _135;
    _89[0].x = frameUniforms.clipFromWorldMatrix[0].x;
    mat4 _92 = _89;
    _92[0].y = frameUniforms.clipFromWorldMatrix[0].y;
    mat4 _95 = _92;
    _95[0].z = frameUniforms.clipFromWorldMatrix[0].z;
    mat4 _98 = _95;
    _98[0].w = frameUniforms.clipFromWorldMatrix[0].w;
    mat4 _101 = _98;
    ...
```

To repro, download [this gist](https://gist.github.com/prideout/8fd1da05cb8eb0aca61565cf6da286fc) and do:

```
glslc -std=310es -fshader-stage=vertex piecewise.glsl
spirv-opt -Os a.spv -o b.spv
spirv-cross b.spv
```

I'm using a fairly recent copy of spirv-tools, here's the output from `glslc --version`.

```
shaderc v2021.2-dev v2021.1-1-g00c8f73
spirv-tools v2021.3-dev v2021.1-48-ge065c482
glslang 11.1.0-203-g0c4c93bf
```

**Comment by s-perron** [comment]
This does what I expected it to.  The spir-v start by loading the source matrix.  Then it sets each element in the result by doing a series of

```
         %36 = OpCompositeExtract %float %34 0 0
         %89 = OpCompositeInsert %mat4v4float %36 %135 0 0
```

Technically the `OpCompositeInsert` is a copy of `%135` into %89, with just 1 value replaced.  However, there is an optimization that can be done when emulating the insert instruction.  Since `%135` will not be used after the insert instruction, `%89` can share the same memory as `%135`, and just overwrite the one value.  A copy is not actually required.  This is a very common pattern, so I believe this is worthwhile implementing in an emulator.  It would also have general applicability.

We could try to improve this particular case.  We could try to identify a chain of inserts that cover an entire object, and replace them with an `OpCompositeConstruct` instruction.  This can work in some cases, but may not work in all cases.  For example, if some of the elements come for the original value in the chain, they would have to be extracted leading to a near copy that cannot be optimized in an emulator.

I think the best solution is to have the "backend" compiler or emulator allocate the ssa values to the same memory or registers, removing the need for the copy.  It is the most general solution.
