### ISSUE TITLE
Adapt SPIR-V fuzzers to take target environment from existing bytes in the binary

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4450]
A number of the libFuzzer fuzzer targets under test/fuzzers interpret the first word of the given binary as a target environment, like this:

```
  const spv_context context =
      spvContextCreate(*reinterpret_cast<const spv_target_env*>(data));
  if (context == nullptr) return 0;

  data += sizeof(spv_target_env);
  size -= sizeof(spv_target_env);
```

This prevents such fuzzers being equipped with a corpus of SPIR-V files to work on: any corpus would have to be adapted so that some target environment word is prepended to the file.

An alternative would be to have the fuzzers take regular SPIR-V binaries as input, and decide on a target environment based on certain bytes of the file.

For example, assuming there are N target environments that we care about:

```
spv_target_env env;
switch (data[size/2] % N) {
  case 0:
    env = SPV_1_0; // or whatever the right enum is
    break;
  case 1:
    env = SPV_1_1; // or whatever the right enum is
   ...
}
const spv_contexgt context = spvContextCreate(env);
```

This would then allow the fuzzers to run with a corpus.

A detail is that probably most of the bytes in the file will be 0, so it might be better to sum a range of bytes and then mod the result of the sum.

@zoddicus would this change seem reasonable to you?

**Comment by zoddicus** [comment]
I agree overall we should change this behaviour. Tint's fuzzers have a similar behaviour that we were discussing changing this morning.

I think we should leave the corpus the way it is, just actual shader files, and have the way we generate the consumed data change.

For dealing with just picking one of a few options, something like you described of summing and moding would work, or using another hashing function + mod.

For Tint, at least, we might want to come up with a method to generate arbitrary amounts of this data, instead of coming up with a custom solution for each situation.

My immediate thought is hash the input data to get an int, and feed that into a pseudo random number generator as the seed. Thus we get variable data, but it is reproduces consistently for a specific input.

**Comment by afd** [comment]
I think doing a hash sounds good. Cool - I'm happy to take this once I get back from holiday.

**Comment by zoddicus** [comment]
I am going to have to write this for Tint, so if I have time before you are back, I will try to make PR for it.

**Comment by afd** [comment]
That would be great - thanks.

**Comment by afd** [comment]
@zoddicus it occurred to me that a hash of the whole file might not be so good because:

- it may inhibit test case reduction: small changes to the file will completely change the decisions that are made according to the hash
- for similar reasons it might fight against coverage-driven fuzzing: a test case that gets new coverage will be put up for mutation, but a small change to that test case may lead to very different behaviour if decisions are made based on a hash of the whole input.

For choosing target environment this might not matter too much. For making more significant choices (like which opt passes to run, which is what one of my upcoming fuzzer will do) it will matter more.

Maybe a hash of the last N bytes would work better?

**Comment by zoddicus** [comment]
That makes sense to me, I'll take that into consideration in my PR, when I write it.
