### ISSUE TITLE
Expose a compile-time constant to determine which version of spirv-tools is being used.

### ISSUE THREAD

**Issue by AWoloszyn** [KhronosGroup/SPIRV-Tools#446]
This is useful specifically when there is an api-breaking change. Something like:

```
   #ifdef SPV_TOOLS_VERSION < X
   #else 
   #endif
```

**Comment by dneto0** [comment]
Right now our versioning is keyed off of a build step.
So for a from-source build we'd be adding a source dependency to the build output tree.  I don't think we have that for our public interface.

For an installed version of the library, we can migrate a generated file to the output install include dir, so that would be easier.

Not clear to me what to do here.
