### ISSUE TITLE
Use submodule to link approriate headers

### ISSUE THREAD

**Issue by abergmeier** [KhronosGroup/SPIRV-Tools#449]
Currently one cannot simply checkout sources and compile.
Would be better to have e.g. the necessary headers linked in a submodule.

**Comment by AWoloszyn** [comment]
There are a number of issues with submodules that I won't go into here. But because SPIRV-Tools is being used inside a number of other projects, we wanted to avoid the introducing them.

It would not be unreasonable however to add a script to fetch our dependencies if necessary.

**Comment by nsubtil** [comment]
@AWoloszyn, I'd be interested to learn more about the reasoning around avoiding submodules. Would you mind elaborating on this?

The current setup seems to make it hard to maintain a consistent tree, which sounds like an issue to me. Any projects that include SPIRV-Tools end up carrying the same drawback, so in a sense, issues are already being propagated to downstream projects.

**Comment by AWoloszyn** [comment]
The biggest issue that I have with submodules is that if a user doesn't `git submodule update --recursive` every time they switch branches they will end up with a submodule that does not match what is in their manifest. 

I do agree that having nothing to keep everything consistent may be unideal as well. What we have just started doing in https://github.com/google/shaderc is have a branch that defines the list of last known good hashes.

If submodules allowed a parent project to check out into a child project's tree (the repo tool allows this), then this could be solved however a project including SPIRV-Tools wants. Since that is not the case, SPIRV-Tools also allows you to move SPIRV-Headers to whatever directory you want. So an enclosing project could, if they choose, have a submodule for both SPIRV-Tools and SPRIV-Headers as siblings, and then in a CMakeLists.txt file or a build system or whatnot, set SPIRV-Headers_SOURCE_DIR to the directory of SPIRV-Headers. SPIRV-Tools should then build just fine.

https://github.com/KhronosGroup/SPIRV-Tools/blob/master/external/CMakeLists.txt

**Comment by antiagainst** [comment]
I see Windows buildbot failures now because we don't pinpoint the exact commit we use for external projects: https://ci.appveyor.com/project/Khronoswebmaster/spirv-tools/build/2195/job/6p37t8fw8jw7i5cd

It likely results from a recent update in googletest trying to fix the `std::tr1` warnings in newer versions of VS2017: https://github.com/google/googletest/commit/887a6c642006aa7475bdedb2b3652feb6a05f417

So I think we may need some mechanism similar to git submodule.

**Comment by AWoloszyn** [comment]
So there was an update to visual studio a few days ago that started making gtest fail. If the compiler on the bots has. updated, git submodule won't help as the old version of gtest was the problem.

**Comment by dj2** [comment]
I've added a DEPS file which lists all of the needed hashes. You can use gclient to sync the repo if desired. I don't think we plan on going to submodules any time soon some I'm going to mark this as fixed.
