### ISSUE TITLE
OSS-Fuzz: infinite loop in spirv-opt, in DeadBranchElimPass::FindFirstExitFromSelectionMerge.

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4508]
OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38172&q=spirv-tools&can=2&sort=summary

The function keeps considering the cycle:

-> 55 -> 56 -> 60 -> 61 -> 55 -> 56 -> 60 -> 61 ...

@s-perron would you be able to take a look?

**Comment by s-perron** [comment]
I believe this is an invalid test case because the cfg is not structured.  I have attached a visual representation of the cfg.  Notice the branch from block 61 to block 55.  That branch is not part of the loop with loop header block 55.  In order to reach block 61 from 55, you have to go through the merge block for the loop, block 56.

@alan-baker Do you agree that this is something that the validator is missing?

![g](https://user-images.githubusercontent.com/31666470/134518291-38b5c0e5-772c-4cf4-9cdf-b156fefe2311.png)

**Comment by alan-baker** [comment]
I agree this seems wrong. I'll take a look.

**Comment by alan-baker** [comment]
The validator isn't able to perform much validation for unreachable blocks. 61 -> 55 looks like an invalid back edge, but the traversal in the validator doesn't qualify it as such because 61 is unreachable.

**Comment by afd** [comment]
Aside: I think there's a strong case for arguing that structurally unreachable blocks should not be allowed at all, *or* that anything goes in such blocks with respect to control flow. (See [here](https://docs.google.com/document/d/13r6xxYYZH2eTYRqRqU1qvlwDgsMwyNeTPFJPjPwR83g/edit#) for what I mean by "structurally unreachable").

**Comment by s-perron** [comment]
Right I missed that 61 is unreachable.  However, it is the merge block for the infinite loop, which places it outside of the construct.  If this is not something that the validator can fix, I can fix dead branch elimination.  Dead branch elimination should also delete the branch in block 61 so later passes do not have to worry about it.

**Comment by alan-baker** [comment]
This is being caught as invalid now. I believe structural dominance fixed it.
