### ISSUE TITLE
OSS-Fuzz: poor performance / high memory usage in spirv-opt

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Tools#4513]
OSS-Fuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38103&q=spvtools_opt_performance_fuzzer%20-label%3ASPIRV-Tools-Tracked&can=2

Given that the shader is fairly small, I think it's worth looking at this one.

@s-perron

**Comment by afd** [comment]
`spirv-opt -O` takes about 4 seconds on my cloudtop.

**Comment by s-perron** [comment]
Almost all of the time is spent in vector-dce.  I can take a look at what is going on.

**Comment by s-perron** [comment]
The problem is that other optimization generate an OpCompositeExtract with 3221225473 for the index.  This would not pass the validator, but spirv-opt does not run the validator between passes.  When vector-dce sees this, it will allocate a bit vector with that many elements, initializing them all to zero.  This is avoided by checking the size of the vector being extract from.  If it is out-of-bounds, then we do not mark that element as live, keeping the bit vector small.
