### ISSUE TITLE
SPIRV optimizer from C

### ISSUE THREAD

**Issue by ProkopRandacek** [KhronosGroup/SPIRV-Tools#4669]
Hello,
Is there a C API header for the optimizer or do I have to use the C++ one?

**Comment by dneto0** [comment]
Thanks for asking.  We never made a C API for the optimizer, mainly due to lack of demand balanced against the additional maintenance cost (all committed code is debt).

For now you'd have to use the C++ API.

I am interested in why you might want it:  Do you plan to call it from C, or from another language such as Python or Rust. The application would be interesting.

Some background: 
- If I remember correctly, linking to any part of the public C++ interface will pull in all the optimizer code.  This leads to code bloat when all you need is a few selected transforms.   Before committing to a C  API I would want to avoid that problem.
- Over the years we have updated the optimizer's internal representation of the SPIR-V module, and I'm glad we never exposed that level of detail so far.  On the other hand I've written some other C++ code that has reached into the internals of the optimizer, so I know there is use for it.

So, if anyone proposes a C API to the optimizer, I would like it to carefully consider some of these refactoring concerns.

**Comment by ProkopRandacek** [comment]
I did plan to call it from C. I ended up writing a small wrapper around functions that I need in Cpp and linking those together.

Thank you for your answer.
