### ISSUE TITLE
Check universal limits (2.17)

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#484]
WIP by @ehsannas

**Comment by ehsannas** [comment]
Universal Limits are described in Section 2.17 of the SPIR-V Spec.

Things that I have committed so far:
:white_check_mark: Characters in a literal string (This is handled by the binary parser)
:white_check_mark: Instruction word count (Also handled by the binary parser)
:white_check_mark: Result <id> bound
:white_check_mark: Number of OpSwitch (literal, label) pairs
:white_check_mark: Number of OpTypeStruct members
:white_check_mark: Number of function parameters, per function declaration
:white_check_mark: OpFunctionCall actual arguments:
 - This will handled automatically due to the previous check. OpFunctionCall takes an OpTypeFunction id as an argument. The validator does check that OpTypeFunction does not take more than 255 arguments. So, if OpFunctionCall takes more than 255 arguments, they will get an error that says "the number of arguments passed does not match the OpTypeFunction signature".
:white_check_mark: Number of Global variables (Storage Class other than Function)
:white_check_mark: Number of Local variables (Function Storage Class)

**Comment by ehsannas** [comment]
:file_folder: Skipped: Execution modes per entry point 
- The total number of execution modes defined in the spec is 36. It would be impossible to exceed the limit for the number of execution modes per entry point (255). In the future, more execution modes may be defined; but I doubt we reach 255 any time soon (or ever).

**Comment by ehsannas** [comment]
:white_check_mark: Validation for OpAccessChain.

**Comment by ehsannas** [comment]
:file_folder: Skipped: OpExtInst actual arguments 
- Any arbitrary instruction set could be imported.

:file_folder: Skipped: Decorations per target \<id\> should not exceed the number of rows in the Decorations table
- The only way to violate this would be to apply the same decorations multiple times.

**Comment by ehsannas** [comment]
:white_check_mark: Validate Structure nesting depth

**Comment by ehsannas** [comment]
:eyes:  Up for review: OpInBoundsAccessChain 
PR #481

**Comment by ehsannas** [comment]
:construction: Work In Progress (WIP): Check Control-flow nesting depth (limit = 1023)

**Comment by dneto0** [comment]
@ehsannas Earlier you said "And we'd also need a data-driven way to parse out the decorations table from the Spec."  Would it be useful to generate iterators for particular enums?  I've got some year-old code for automatically generating iterator tables for opcodes.  That could be adapted for enums in general.

**Comment by ehsannas** [comment]
@dneto0 If there are other features that can also benefit from it, then I'd say it's useful to take that code and adapt it for enums in general. If it only serves this single check, it may not be worth the effort since violating the limit of number of decorations per \<id\> is quite difficult to do even in a hypothetical spirv program.

**Comment by dneto0** [comment]
@ehsannas Right.  There's a reason I've let it languish for a year.   :-)
Perhaps the right thing to do is to add a TODO for this check and maybe file an issue/Note in the project.

**Comment by dneto0** [comment]
:white_check_mark: Control flow nesting depth.  https://github.com/KhronosGroup/SPIRV-Tools/pull/511
Skipped the case of unstructured control flow since it's not clear how to count nesting depth.

**Comment by dneto0** [comment]
All that's left is:

* Indexes for OpPtrAccessChain, OpInBoundsPtrAccessChain, OpCompositeExtract OpCompositeInsert

Note that composite extract and insert can exceed the nesting depth of a struct if you have intervening arrays.
Funny but nothing limits the array nesting depth.  :-)

**Comment by ehsannas** [comment]
✅ OpPtrAccessChain
✅ OpInBoundsPtrAccessChain
✅ OpCompositeExtract
✅ OpCompositeInsert

**Comment by ehsannas** [comment]
I believe we can mark Universal Limits (2.17) as done! :-)
