### ISSUE TITLE
spirv-dis: Don't stop disassembling when ID is 0

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/SPIRV-Tools#4885]
spirv-dis currently aborts if a zero id is used, but that makes debugging broken shaders harder. It would be more useful if it simply printed the zero id.
Example:
[FF_VS_dfb48bd64aac275e77358e89aff8bcb0d7883593.spv.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/9274832/FF_VS_dfb48bd64aac275e77358e89aff8bcb0d7883593.spv.zip)
spirv-dis currently fails with `error: line 402: Id is 0`

**Comment by DadSchoorse** [comment]
Ah I guess this is a duplicate of #4229.

**Comment by s-perron** [comment]
Our internal representation of an instruction uses 0 as a special value. Instructions with no result are indicated by a result id 0 for the result id and type id in the instruction. Those are the times we actually fail. If 0 is an operand id for the instruction, then we emit a message, but it will continue.

I think that trying to implement this would require some type of hack, like automatically changing the 0 to some other value. However, that could be confusing because the disassembler will be changing the spir-v, and would possibly cause other error. There is no elegant solution to this problem.

`spirv-dis` already print all of the previous instructions. That will have to do.
