### ISSUE TITLE
OSS-Fuzz: Enum Invalid-enum-value

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/SPIRV-Tools#4960]
In `spirv-val` there is a lot of usage of `GetOperandAs` which does a `static_cast` to the enum based on a value read from the binary. Doing a `static_cast` to a value which is not in the enum is undefined.

This casting happens all over the place in spirv-val.

Either we need to create wrapper functions using a switch to only convert values which are actually in the enum or we can disable the sanitizer with something like https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#disabling-instrumentation-with-attribute-no-sanitize-undefined.

See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42610

**Comment by alan-baker** [comment]
So if I understand this correctly, if there is a well-defined underlying type then the cast ok if it is a valid value of the underlying type?

If so, maybe the validator should switch to using spirv.hpp11 since those enums seems are defined as classes with defined underlying types. It would be a bunch of churn but maybe it would eliminate all these types of bugs.

**Comment by alan-baker** [comment]
Initial testing confirms using spirv.hpp11 can fix this particular case. I'd expect it should work generally, but it needs testing. Ideally all of SPIRV-Tools could shift to C++ 11 headers. Not sure what's exposed where though.
