### ISSUE TITLE
Please add install packages to each release

### ISSUE THREAD

**Issue by Jake-Shadle** [KhronosGroup/SPIRV-Tools#4967]
Currently the releases (when they actually happen, at the time of this writing 2022.2 is the latest release even though 2022.3 and 2022.4 have both been tagged) are just a snapshot of the source code. However the downloads for the install.tgz/zip, if one wants to quickly extract the binaries in their own [CI](https://github.com/EmbarkStudios/rust-gpu/blob/4b10bf5db12bc4bd716bcd1476885b832b6a9dee/.github/workflows/ci.yaml#L25-L36), requires finding obscure GCS urls to match what version of the tools you want to use, which is a giant pain the ass when compared to just attaching those binaries to the releases themselves for either users or tools to easily find and download. Or if that is hard/impossible, at least having _some_ kind of stable, predictable URL that one can use eg. `https://storage.googleapis.com/spirv-tools/install/v2022.4/<target_triple>/install.<ext>`, at least for the tagged releases.

**Comment by Keenuts** [comment]
(@dneto0 since I'm paraphrasing you)

We don't have an extensive QA on those release. They are just provided as additional conveniences, on a best-effort basis.
I do believe however that we run a bit more QA for LunarG SDK releases (@dneto0 to correct me if I'm wrong)

If you want an installer, I'd recommend 2 options:
 - rely on your distribution package manager.
 - get it from LunarG's SDK (https://www.lunarg.com/vulkan-sdk/).

**Comment by s-perron** [comment]
We have updated our checklist for release. Hopefully we will not fall behind on publishing the releases.  As for install packages, we will not be providing install packages. Our release schedule is in sync with the Vulkan SDK cycle. That is, the latest Vulkan SDK contains the latest release of SPIR-V tools. If you do not want to build from source, I recommend you get it from there.
