### ISSUE TITLE
glslangValidator: Error: -Os not available; optimizer not linked (use -h for usage)

### ISSUE THREAD

**Issue by erleria** [KhronosGroup/SPIRV-Tools#5103]
Hi,

Just the -Os option doesn't work for shader compilation, I have the following error:
`glslangValidator: Error: -Os not available; optimizer not linked (use -h for usage)`

but it is totally fine with spirv-opt:

```
$ spirv-opt -Os
error: -o required
```

If spirv-opt is the optimizer, how both should be linked, then? Aren't they two different binaries?

I am on debian 11

**Comment by erleria** [comment]
Ok the issue is definitely not solved and is maybe related to the SDK tarball.

An alternative solution (in case some people are in that situation):
I don't get the mentioned error by using /bin/glslangValidator (from apt-get install) and it works fine with vulkan sdk binaries until version 1.2.189 (seems to not work properly after that)

If you use version 1.2.19x or above, do apt-get install glsl-tools and modify the `PATH="$VULKAN_SDK/bin:$PATH"` to `PATH="$PATH:VULKAN_SDK/bin"` in your .bashrc or setup-env.sh (provided in the tarball), at least it worked for me

**Comment by s-perron** [comment]
spirv-opt can be used as a library as well as a standalone binary. glslangValidator can be compiled with spirv-opt as a library, but and option has to be turned on a build time.  See https://github.com/KhronosGroup/glslang/blob/c43008e82993b460944533656a1d4a4467aa17af/CMakeLists.txt#L310.

Other options are to use `glslc` to compile the shaders, which is in the SDK. 

I'll close this issue because it is more of a glslangValidator documentation issue. Open an issue [here](https://github.com/KhronosGroup/glslang).The help says that -Os is available when it is not. Also, lunarg maintains glslang and build the SDK. You could also ask them why they do not enable optimizations in the SDK.

FYI @greg-lunarg.
