### ISSUE TITLE
spirv-opt: scalar-replacement can produce invalid SPIR-V with buffer references

### ISSUE THREAD

**Issue by arcady-lunarg** [KhronosGroup/SPIRV-Tools#5196]
Running spirv-opt on the shaders from https://github.com/KhronosGroup/glslang/issues/3188 with -Os results in SPIR-V validation error as such: 
```
error: line 122: Result type (OpTypePointer) does not match the type that results from indexing into the composite (OpTypePointer).
  %678 = OpCompositeExtract %_ptr_PhysicalStorageBuffer_MeshVertexNormals %414 0
```
Additionally passing --validate-after-all points to the scalar-replacement pass
```
error: line 189: OpVariable 677: expected AliasedPointer or RestrictPointer for PhysicalStorageBuffer pointer.
  %677 = OpVariable %_ptr_Function__ptr_PhysicalStorageBuffer_MeshVertexNormals Function

error: line 0: Validation failed after pass scalar-replacement=0
```
The SPIR-V before and after optimization are attached, these are from a cut-down version of the shaders in the original glslang issue.
[files.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/11237236/files.zip)

**Comment by arcady-lunarg** [comment]
It appears that what is happening is that there are two separate PhysicalStorageBuffer types where the contents of the pointed-to struct are structurally identical but the struct types are distinct, and those are being used interchangeably when they shouldn't be.

**Comment by greg-lunarg** [comment]
Yes. This has tripped up the shader tool chain before in different ways. That is, two SPIR-V types that are structurally identical, but are (correctly) considered different only because they have different result ids.

There are probably a couple different ways to deal with this. One way (perhaps the best way) is to create a type canonicalization pass such that all type uses in the module use only the type registered in the TypeManager and remove unused types afterward using a simple, static, dead code elimination. In essence, a pass that eliminates redundant types. We would probably call it near the beginning of any optimization recipe.

We probably would not want to use the aggressive dead code elimination here to get rid of the unused types. Rather just do a simple single pass from the bottom of the module to the top, eliminating unused instructions as you go. You might have to do first pass to record uses by phi functions and other forward declarations. I am not sure if there is such a pass in spirv-opt. You might have to write it.

**Comment by s-perron** [comment]
Since we want to allow anyone to use their own order for the optimizations, I would like to see if we can fix this in scalar replacement first. The solution of adding another pass to canonicalize would be nice, but adds extra knowledge that users picking their own pass would have to think about. I would prefer to not have to do that if we do not have it.

**Comment by arcady-lunarg** [comment]
The thing is it's not really an issue with scalar replacement per se, it's going to give the same problem with any pass that add instructions referencing these types, because there are 2 types with distinct IDs that are being represented by a single type in the type manager.

**Comment by greg-lunarg** [comment]
> Since we want to allow anyone to use their own order for the optimizations, I would like to see if we can fix this in scalar replacement first. The solution of adding another pass to canonicalize would be nice, but adds extra knowledge that users picking their own pass would have to think about. I would prefer to not have to do that if we do not have it.

I was just imagining the possibly cascading extra logic that might be required to deal with this situation on an ad hoc basis. It seems much cleaner to just get rid of the redundant types to begin with.

But you are right. We don't want to require users to have this extra knowledge.

What if we just hard coded calls at the beginning of scalar replacement to the proposed passes to clean up redundant types?

Or what if we improved the generation of the TypeManager to get rid of redundant types.

**Comment by s-perron** [comment]
> Or what if we improved the generation of the TypeManager to get rid of redundant types?

We have talked about this in our team, but did not get to a fully satisfactory solution. The problem is that some types can only be defined once, while other types can be defined multiple times. We wanted something like the type manager so that we did not accidentally create multiple 32-bit unsigned integer types. We did not realize at the time how much of a problem this might cause, and we used the type manager in places we should not have. If I were to reimplement it, I would probably limit the type manager to just the type that could not be duplicated. 

Given what we have, I kinda want to add a restrict to certain functions, and add an assert to `TypeManager::GetId` if it is used on a type that could have a duplicate. This should let us know all of the places this type of error could happen, and then we can fix all of them. I'll look into this next week.

If we were to just add the deduplication to scalar replacement, then it would not fix all uses of the type manager, and is probably just as easy to get scalar replacement to stop relying on the type manager.

**Comment by s-perron** [comment]
The problem is not in scalar-replacement. The validation error after scalar replacement is picking up that the original shader is invalid, even if the validator does not say so.

The spir-v module contains:

```
%Mesh = OpTypeStruct %_ptr_PhysicalStorageBuffer_MeshVertexPositions %_ptr_PhysicalStorageBuffer_MeshVertexNormals
%_ptr_Function_Mesh = OpTypePointer Function %Mesh
%meshData = OpVariable %_ptr_Function_Mesh Function
```

From my understanding `%meshData` must have either an `AliasedPointer` or `RestrictPointer`. See [here](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#:~:text=If%20the%20type%20an%20OpVariable%20points%20to%20is%20a%20pointer%20(or%20contains%20a%20pointer)%20in%20the%20PhysicalStorageBuffer%20storage%20class%2C%20the%20OpVariable%20must%20be%20decorated%20with%20exactly%20one%20of%20AliasedPointer%20or%20RestrictPointer.).

When scalar replacement replaces `%meshData` with two variables (one for each member), it does not add a decoration for the new symbols, and the validator starts to complain.  After adding `AliasedPointer` to `%meshData`, spirv-opt produces spir-v that validates.

The first task is to fix glslang. Then there is probably a hidden bug in spirv-tools that I will try to find another way to track down.

**Comment by s-perron** [comment]
> The problem is not in scalar-replacement.

Sorry, this statement is too broad. There is a problem when what I believe to be invalid code. If the decoration is added, scalar replacement does not do the replacement because it does not know what to do with the decoration.

There is a bug in scalar replacement. There is code that will do a linear search through all of the types to find the correct pointer type if it is possible that the type manager returns the wrong one. However, that check is not totally correct.

I'll write a PR that will teach scalar replacement what to do with the decorations, and that will fix the incorrect check.
