### ISSUE TITLE
Scalar replacement of aggregates

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#539]
Child of https://github.com/KhronosGroup/SPIRV-Tools/issues/457

**Comment by dneto0** [comment]
WIP by @greg-lunarg

**Comment by greg-lunarg** [comment]
This work evolved into the pass InsertExtractElimPass.

Rather than do scalar replacement, which would decompose every structure member into scalar variables (resulting in significant code explosion, only to be ultimately eliminated), we took a different approach. We converted all constant index access chain loads and stores into their equivalent loads and stores plus insert and extract (LocalAccessChainConvert). So loads and stores are kept at the struct/array level, much more manageable size-wise. Once trivial loads and stores are eliminated (LocalSingleBlockElimPass, LocalSingleStoreElimPass), we are left with sequences of inserts with extracts directly operating on them. With little analysis, this pass replaces such extracts with the corresponding inserted value.

InsertExtractElimPass has been integrated. This item is done.
