### ISSUE TITLE
A copy of what?????

### ISSUE THREAD

**Issue by AnonymousRonin** [KhronosGroup/SPIRV-Tools#5509]
What kind of stupid shit is this?  A copy of what.  Spirv-headers were compiled and installed before I ever downloaded this.  It  can't find them??  Then what good is this software anyways?? 

" SPIRV-Headers was not found - please checkout a copy under external/. "

**Comment by s-perron** [comment]
Please see https://github.com/KhronosGroup/SPIRV-Tools?tab=readme-ov-file#getting-the-source. There is a PR that we had to revert that would have allowed using an install version of spirv-headers. Note if that if you use an installed version there is no guarentee that it will work because it could be too old.
