### ISSUE TITLE
Info about SPV_KHR_16bit_storage?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Tools#565]
Hi,
don't know if correct place to ask but seen a commit here referencing SPV_KHR_16bit_storage, but can't information anywhere about it? is this extension still in the works?

**Comment by dneto0** [comment]
It was published yesterday.
See https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_16bit_storage.html

**Comment by oscarbg** [comment]
thanks didn't found the link!

any way still have two questions:
1) I'm still new to Vulkan but I can't find a corresponding KHR_16_bit_storage Vulkan extensión: how to know then if a implementation supports that SPV extensión?

2)in your commit you mention:
"requires the Float16 or Float16Buffer capability  or an extension that explicitly enables 16-bit floating point"
but seems Float16 or FLoat16Buffer capability isn't on Vulkan specification of capabilities to check and vulkaninfo tool from SDK don't check this support.. so where Float16 and  Float16Buffer caps are defined?

also about "an extension that explicitly enables 16-bit floating point"
currently there is one only and it's VK_AMD_gpu_shader_half_float , right?

**Comment by dneto0** [comment]
You're right.  A SPIR-V extension needs a corresponding extension in a client API to enable that SPIR-V extension.  Currently no client API has an extension that enables SPV_KHR_16bit_storage.

Float16 and Float16Buffer  are *defined* in SPIR-V, and *enabled* by the provisional OpenCL 2.2 environment spec
https://www.khronos.org/registry/OpenCL/specs/opencl-2.2-environment.pdf 

I used the phrase ".. an extension that explicitly enables 16-bit floating point" as a catch-all phrase to include VK_AMD_gpu_shader_half_float (and corresponding SPV_AMD_gpu_shader_half_float) or any other ones that will appear.  It's a vague phrase since I didn't want to have to update the message every time a new extension is published.

Note that the validator does support the AMD extensions.  In particular, the validator won't recognize that certain rules have to be relaxed for those extensions.

**Comment by dneto0** [comment]
See the published VK_KHR_16bit_storage extension: https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/vkspec.html#VK_KHR_16bit_storage 
or in its raw form https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/doc/specs/vulkan/appendices/VK_KHR_16bit_storage.txt
