### ISSUE TITLE
Change to CMake install rule for the include directory?

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/SPIRV-Tools#5751]
It seems like there are lots of missing headers in the install/include directory now. For example MachineIndependent seems to only come with Versions.h now, and is missing other useful headers such as iomapper.h.
SPIRV is missing SpvTools.h is another example of a useful header that's no longer copied.
Is there a new workflow to follow?

**Comment by mbechard** [comment]
Ugh, wrong project here too

**Comment by arcady-lunarg** [comment]
The pruning of headers was intentional, but it is possible that I may have been too enthusiastic with cutting things down and am certainly open to adding things back if someone complains that they need them. Mostly the goal was to avoid exposing all the private insides of the compiler as a public API because it would be impossible to maintain a stability guarantee there. I will take a look at those two headers and either add them back in or find some way for you to access the equivalent functionality.
