### ISSUE TITLE
Inconsistent behavior before and after spirv-opt on float/uint conversion

### ISSUE THREAD

**Issue by mitdemverkaufer** [KhronosGroup/SPIRV-Tools#5775]
Converting a float to uint and then back to float gives inconsistent result before and after running spirv-opt.

Consider the following expression:

```c
float t = -1.0;
float c = float(uint(t));
```

When a floating-point variable `t` holds the value of -1.0, the expression `float(uint(t))` gives 0.0 without optimization, but is folded to the constant 4.2949673e+09 after running spirv-opt with the `-O` flag.

However, when slightly tweaking the value of `t` to be between -1.0 and 0.0, e.g., -0.9999, the spirv-opt optimization folds the expression to 0.0, which is consistent with the unoptimized version.

**Steps to reproduce**:

I made a minimal fragment shader that simply outputs the value of `float(uint(t))` as the fragment color. I also provide a Vulkan application that loads the fragment shader. The full package can be downloaded [here](https://drive.proton.me/urls/DREBMKYH5C#iYYMcO5gwo0Q). It also contains a detailed README file to show the execution environment, reproduction steps and analysis with `spirv-dis`. It should take less than a minute to reproduce the issue.

**Comment by s-perron** [comment]
This is undefined behaviour. When you cast `-1.0` to a uint, there is no `-1` for uint. From the [spir-v spec](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpConvertFToU), this would be undefined. You cannot represent a negative value as a uint.

You need to change your shader because you cannot count on any particular result being consistent across devices, driver versions, or compilers.
