### ISSUE TITLE
Spirv-opt does not optmize array accesses inside ByteAddressBuffer with no constant index

### ISSUE THREAD

**Issue by webez** [KhronosGroup/SPIRV-Tools#5798]
Hi,
I have seen that when I have code like this

`struct StructWithData 
{ 
    uint2 data1 ; 
    float data2 ; 
}; 

struct StructWithArray 
{ 
    uint4 pad ;
    StructWithData data[ 4 ] ;   
}; 

ByteAddressBuffer byteAddressBuffer ; `

and data is accessed with a non constant index, Dxc produces OpAccessChain for each of the positions in the array and each of the members of StructWithData. The problem is that I haven´t found any pass in spirv-opt that can simplify OpAccessChain  with non constant index. The result is poor spirv/spirv-cross code that is only fixed replacing ByteAddressBuffer  with StructuredBuffer or by using Loads that access data inside StructWithData  directly.

Here is an example in shaderplayground

https://shader-playground.timjones.io/971324544cf3403ad70514e4d2887948

**Comment by s-perron** [comment]
This is an awkward one. Because of the hacky implementation of ByteAddressBuffer, the load of the struct turns into a lot of code, and create odd code patterns. We have to load all elements of the struct separately, bitcast to the correct types, and then build it.

Now we run into a problem. We do an access chain to pick which element of the array to loads. If the index is a constant, we know exactly with one is chosen, and it is easy to optimize. Hopefully the drivers are able to optimize it better since they would have more general instructions. I don't think there is anything we can do in the optimizer.

To get better code, we would need DXC to generate better code. The options for that (neither of which will be done in DXC, but we can consider in clang) are:

1. Use [untyped pointers](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_untyped_pointers.html) to implement ByteAddressBuffers. This is the ideal and longer term plan, but they are not available on any hardware yet.
2. Have DXC treat the ByteAddressBuffer::Load as if it returns a constant l-value to the memory location. That is do not do the load of the struct, but just keep a pointer to it. Then apply all of the access chains to it. The problem with this is that it will create a lot of special cases in creating the access chains. All of the accesses to a nested aggragate will have to add to the index in the single access chain for the variable instead of creating separate access chains or indices for each access. Also the access is based on the word offset of the member instead of its position in the OpTypeStruct. This would be a huge mess in the code.

The best we can do is wait for untyped pointer to be available, and we will using them in the clang HLSL compiler. Sorry about that.

Compiler explorer link (loads faster): https://godbolt.org/z/sv47Mqcsq
