### ISSUE TITLE
Add a way to retain a DefUseManager between passes, if a pass promises to keep it up to date during operation.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#608]
I'm discussing some ideas with @antiagainst and @greg-lunarg on how to do this well.

**Comment by dneto0** [comment]
LLVM does a lot of work to make def-use info very very compact and fast to access.  To first order it's only right to retain it between passes when a pass specifically maintains it properly.  So the question is how to do that.

Considerations and design ideas:
- Who holds onto the data?  ir::Module seems a natural choice but it feels like that would overload its responsibilities.  Better to get the functionality by composing from other objects.
- So I'd rather have a new object, an "optimization context" if you will.  I'd add Pass::ProcessInContext method that it takes a pointer to the optimization context rather than the module.  
    - the context object contains the module, the def use manager, and anything else that is carried from one pass to the next.
- We can then make passes templated over its macro behaviours such as "I maintain the def use manager", or "i properly maintain the Module ID bound"
- The default (existing passes) would have the default instantiation which is "I don't maintain the def use manager", and "i don't maintain the module ID bound".
- Follow LLVM's pattern:  Instead of creating a DefUseManager on its own, a  pass requests it from the context object.  The context has enough info to know whether it has to create one from scratch or whether it can reuse the one it already has.  
- I don't think we need it yet, but if necessary we can add an explicit "InvalidateDefUseManager" method on the context object in case a pass completely reconstructs the def use manager during its operation.
- Fortunately the public API exposes PassToken instead of the raw Pass itself. So we are free to update the Pass API.  :-)

**Comment by dneto0** [comment]
More thoughts:

* Clearly the optimization context is good for any kind of stateful analysis, such as (for example) decoration analysis
* For safety sake, invert the invalidation API so that by default the optimizer context assumes that pass invalidates all analyses.  But a pass that knows it maintains a particular analysis can use a call back to indicate that it has kept it up to date.

**Comment by dnovillo** [comment]
I'm starting to look at adding some new options to spirvopt.  Analysis invalidation will likely affect my work.  I can take a stab at fixing this first.

**Comment by dneto0** [comment]
cc @s-perron

**Comment by dneto0** [comment]
More thoughts:

- I think we should change be more bold and remove the existing Pass::Process(ir::Module) method to Pass::(ir::IRContext) (or whatever the new class name is)
- We now have a real DecorationManager class.
- When we add a types-and-constants pool (or pools), it should be owned by the IRContext
- The IRContext should probably be used as a facade for common operations in such a way as to keep all the data consistent with each other.  E.g.   IRContext::RemoveDecoration (blah blah blah) would both update the internally maintained decoration manager *and* the def-use-manager.

**Comment by s-perron** [comment]
I'm going to start working on this.  I'll try to think of a design, and add it to the issue.  If anybody has any requirements besides what has been stated here let me know.  This will be more general than just the def_use manager.  I'll want to create something to keep the use-def chains (separate from def-use), def-use chaings, CFG, decorations manager, etc..

**Comment by dnovillo** [comment]
Sounds good.  I'm in the middle of refactoring the SSA rewriter into
MemPass (https://github.com/KhronosGroup/SPIRV-Tools/issues/893).  This has
forced me to move up bits that include the def-use manager.  I should be
done later today, but this may interfere with your plans.  The idea is to
leave the def_use_mgr_ field in class Pass for now.  As well as some other
CFG-specific functions (like IsLoopHeader).

**Comment by dneto0** [comment]
Yes, there are other small functions that are a good fit for the "IRContext":   e.g. MergeBlockIdIfAny, ComputeStructredSuccessors, and friends.  See my review https://github.com/KhronosGroup/SPIRV-Tools/pull/916#pullrequestreview-71636624 

I agree we should transform the code in small steps.

**Comment by s-perron** [comment]
# Background

When a compiler optimises code, it often needs to analyze the code to extract extra information.  Some examples are the def-use chains, use-def chains, and control flow graphs.  It is also helpful to organize the code in a way that make it easier to access.  The DecorationManager in spirv-opt is an example of that.

There are several challenges with the current approach:



*   Runtime cost:  Each pass must rebuild these things themselves if they want to use them.
*   Complexity: When several helper objects are used, they must be updated consistently when a transform updates the code in a module.  Updating them consistently and correctly is complicated when one of those helper objects performs the code transform.  
    *   For example, see [SPIRV-Tools PR 919](https://github.com/KhronosGroup/SPIRV-Tools/pull/919#pullrequestreview-72334410), where the DeocrationManager is trying to provide an API that updates the module but then can easily fail to update the DefUseManager. 

# Objective

We propose a new class, spv::ir::IRContext.  It is responsible for build, updating, invalidating and deleting these data structures.

One IRContext instance will survive through the entire compilation, and will given to every pass.  The IRContext object is the preferred API surface for getting information about a module and for mutating it:



*   When a pass needs information, it can ask the IRContext to supply it.
*   When a pass needs to update the module or analysis in a nontrivial way, it should do it via the IRContext.  (That way the IRContext can keep *all *the dependent analyses consistent.)

Once this is implemented, passes will be given an IRContext, which includes the module, instead of a module itself.


# Design Overview

The IRContext will be the class that ties a module and all of the analyses together.  Below is a general layout of what it could do.  We do not have to implement all of the analyses immediately, just refactor those that we already use in many places.



*   When created, it will be given a module, for which it will take ownership.
*   The PassManager will be given an IRContext to run on.
*   Each Pass will take an IRContext to run the pass on, replacing the module it currently get.
    *   The Pass::Process(ir::Module) method is replaced by a Pass::Process(ir::IRContext)
*   The IRContext will keep track of the analyses.
    *   It will know if they are valid or invalid.
    *   It will build (or rebuild) when needed.
    *   It will provide fundamental operations on the IR that will automatically (consistently) update the analyses.
*   Pass will get two list
    *   One describes the analysis it needs.
    *   The other the analyses it preserves.
    *   The default will be that is needs everything and preserves nothing.
    *   Classes extending Pass will have the ability to specialize those list.
    *   Hidden to the classes extending Pass
        *   Before starting ::Process(), the IRContext will be asked to build analyses that are needed.
        *   After returning from ::Process(), if there were any changes, the IRContext will invalidate analyses as needed.
*   Analyses the IRContext could manage
    *   Def-use manager
    *   Decoration manager
    *   Control flow graph
        *   This could also include loop data.
    *   Type manager
    *   Constant manager
    *   Call graph
*   Analyses it will not manage because they are not used often enough
    *   Dominator trees
        *   Most optimizations that would normally need dominator trees are able to get away without them because of the structured control flow that is guaranteed for shaders.
    *   Control dependence graph
        *   Very rarely needed.  Not worth the complication in the IRContext.
*   Operation on the IR that the IRContext should perform (or be informed of).
    *   Foundational tasks
        *   Inserting a new instruction
        *   The IRContext should be asked to delete an instruction.
        *   Replacing or updating an instruction.
        *   Could this all be done with register and deregister instruction?
    *   Utility tasks
        *   Removing all names and decorations for an id or instruction.
        *   Replacing all uses of one id with another.
        *   Deleting a basic block, and function.
        *   Create new basic block and function.
*   Many operations should be provided by analyses themselves and not the IRContext.
    *   Traversals of the control flow graph or call graph should not be done by the IRContext.
    *   Looking up information like getting the definition of an id should come directly from the def-use manager.
    *   In general, read only operations should not be done by the IRContext.
    *   In general, traversals that apply a given function on every object are not done directly through the IRContext.  The IRContext should be available to the given function if that function changes the IR.

**Comment by s-perron** [comment]
Suggestions already made:

1. Should the analyses be build when accessed instead of before the pass?
     1.  This has the advantage of not building if there is an early exit or if something is only used in a corner case.
      1. Could help us avoid listing things ahead of time, make it less likely there will be a bug because something is used that was not requested.
1. Something might be better in the IRContext instead of asking the analysis in case we want to change the implementation
    1. For example, we will likely want to split def-use chains and use-def chains into separate data structures.  Asking the context for the definition of an id would make that change easier.

**Comment by s-perron** [comment]
First part is in PR https://github.com/KhronosGroup/SPIRV-Tools/pull/934.

**Comment by s-perron** [comment]
I believe this is essentially done. @dneto0 Let me know what else you want done as part of this issue.  Other analyses can be added to the IRContext by other issues.
