### ISSUE TITLE
Verify upper bits of literal numbers that aren't a multiple of 32 bits.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#660]
See 
https://github.com/KhronosGroup/SPIRV-Tools/pull/659

**Comment by jcaraban** [comment]
@dneto0, I think I can handle this issue.

Shall the verification happen at parsing/operand level, before the call to ProcessInstruction( )?
Since multiple instructions use literals, one single check somewhere in Parser::parseOperand( ) will be easier than individual validations for all those instructions with literals, right?
Does this issue apply to SPV_OPERAND_TYPE_TYPED_LITERAL_NUMBER only?

It seems to me that the validation code should go either in the switch of parseOperand( ) or in setNumericTypeInfoForType().
