### ISSUE TITLE
Constant folding, propagation, and dead code elimination passes? 

### ISSUE THREAD

**Issue by benvanik** [KhronosGroup/SPIRV-Tools#664]
(asking about these as one issue - but I can file separate issues if desired)

I'd be really nice if some common (and cheap) optimizations could be added to the optimization passes available in SPIRV Tools.

Particularly, I'm seeing code like the following from glslang passing through the SPIRV Tools optimizer untouched and it makes me sad (these are dumped from SPIRV bytecode by spirv-cross):
```
// single use constant retained as a variable
vec4 some_const = vec4(1.0);
gl_Position = pos_attrib + some_const;
// constant add zero not eliminated
gl_Position = pos_attrib + vec4(0.0);
// constants not folded, divide by 1 not eliminated
gl_Position = pos_attrib / (vec4(1.0) + vec4(1.0));
// unreachable expression not eliminated
if (false) { gl_Position = vec4(0.0); }
```

glslang produces things like this (as it seems to perform no optimizations of its own after the preprocessor runs), and using specialization freezing/substitution passes in SPIRV Tools will also produce quite a bit. It'd be nice to trim these down both for the size of SPIRV files as well as the complexity of the SPIRV passed to drivers. I've also found such passes helpful for making other passes more useful/applicable (like the mem2reg pass that's happening in a pull request), as things like memory address/array index calculation can often be simplified or evaluated as constants early on.

Are there plans for passes like these? (I don't see any on the kanban) Are they considered within scope of SPIRV Tools? I'd really like to avoid relying on something like LunarGLASS (and all of LLVM) for optimizations that are fairly quick to perform and don't require more than what's in val/* now (Instruction has uses(), etc).

**Comment by dneto0** [comment]
Yes, this is in scope for SPIRV-Tools.  It's understood that Glslang is purely a front end in this respect.
You're right I haven't put them in the Kanban board.  :-(

We just need to find the time to make these. @greg-lunarg has a sequence of optimizations that he's pushing into SPIRV-Tools, but I don't know the overlap with your list.

Just the other day someone mentioned simple strength reduction on powers of two, e.g.  % 8 becomes shift right by 3 bits.

**Comment by greg-lunarg** [comment]
I do have a number of size/instruction reducing passes that are written and running on real code and I am working as fast as possible with David to integrate them. See PRs #651 and #656 as the most recent. I also recently added the inlining pass as part of this series. They are somewhat documented by the placeholder issues 538 through 542, although they have evolved a little since these were first posted. Ultimately, the goal is to eliminate where possible all statically referenced function scope variables and their references and all dead control flow (eg. your if(false) above). I have also added consolidation of all uniform references where possible. These will continue to appear over the coming weeks.

I have not yet addressed the constant folding you mention above. It is on my "possibilities" list, but is not yet confirmed.

**Comment by dneto0** [comment]
cc: @nvining-work

**Comment by dneto0** [comment]
The spec constant op folding pass has a bunch of code that can be refactored and reused for this, I think.

https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/fold_spec_constant_op_and_composite_pass.cpp

**Comment by dnovillo** [comment]
This should be handled by the existing folder, CFG cleanup and the upcoming constant propagator (#889)

**Comment by s-perron** [comment]
I believe this is done.  If something is still missing please open a new issue.
