### ISSUE TITLE
More standard to use branches rather than tags for versions?

### ISSUE THREAD

**Issue by hughperkins** [KhronosGroup/SPIRV-Tools#683]

**Comment by dneto0** [comment]
SPIRV-Tools isn't really branched.  The top-of-tree will use/manipulate any released version of SPIR-V.

The tags you see in the repo were made in early days to indicate a revision that first supported that particular SPIR-V spec revision.  Nowadays we want people to just use top-of-tree.

**Comment by dneto0** [comment]
Additionally, we don't do concurrent development on older branches.  Guidance is always use and develop on top of tree.  If there's a bug in a tagged version, fix the bug on master and migrate to master.

This ought to work because we try very hard to not break intended functionality.  (Actually, it's usually laziness.)

That said, Hyrum's Law tends to kick in: https://www.hyrumslaw.com/
