### ISSUE TITLE
Global value numbering.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#700]
Should eliminate duplicate computed values, e.g. in constants section.
Cover Undef cases as well.  Extra undefs could be introduced by Type2Undef method in https://github.com/KhronosGroup/SPIRV-Tools/pull/691

**Comment by dneto0** [comment]
See also opportunity in IfThenElse test in local_ssa_elim_test.

in vec4 BaseColor;
vec4 v;
if (c) { v = BaseColor * 0.5; } else { v = BaseColor + vec4(1.0); }

Results in redundant load of BaseColor.    Could be eliminated with GVN on Input storage class because it's constant (?)

**Comment by s-perron** [comment]
@dneto0 I implemented a GVN based commoning algorithm, but it will not get this case.  The reason is that BaseColor is not loaded multiple times on the same path.

Usually commoning algorithms want to be "lazy".  That is they try not to compute (or load) a value too far before its use because that needlessly increases register pressure.  If you really want to get this case, let me know, and we can discuss how we could do it.

**Comment by dneto0** [comment]
Never mind. Your commoning algorithm is good enough!
