### ISSUE TITLE
Constant folding.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#709]
Claimed opportunity in #664

**Comment by s-perron** [comment]
I have looked for more opportunities to do constant folding.  I modified the folding code to print the opcode of an instruction every time it identifies all of operands are constant and the folder does not fold the instruction.  Here are the results from the three sets.  This is using master as of right now (90e1637ce43a6f53a6961f640e5096c71a4dee76).

Note that some of these will fail to fold because of type of the operand.  For example, the IAdd instruction will only get folded for scalars, and not vectors.

@alan-baker FYI.  This is what we discussed today.

Set 1:
- [ ]       1 ConvertUToF
- [ ]       5 Dot
- [ ]      22 Select
- [ ]      28 VectorTimesScalar
- [ ]     124 Bitcast
- [ ]     145 ConvertSToF
- [ ]     555 FNegate

Set 2:

- [ ]       1 Not
- [ ]       2 CompositeInsert
- [ ]       2 INotEqual
- [ ]       3 BitCount
- [ ]      10 ConvertFToS
- [ ]      15 Dot
- [ ]      20 ConvertSToF
- [ ]     119 VectorTimesScalar
- [ ]     125 ConvertFToU
- [ ]     152 ConvertUToF
- [ ]     192 Bitcast
- [ ]     235 Select
- [ ]     888 FNegate

Set 3:

- [ ]       1 CompositeInsert
- [ ]       1 IMul
- [ ]       1 Select
- [ ]       3 IAdd
- [ ]      24 MatrixTimesVector
- [ ]      27 ConvertFToU
- [ ]      73 Bitcast
- [ ]     235 ConvertSToF
- [ ]     856 VectorTimesScalar
- [ ]    1938 Dot
- [ ]    6307 ConvertUToF
- [ ]    7422 FNegate

**Comment by s-perron** [comment]
@jaebaek I'll do `OpDot`.

**Comment by jaebaek** [comment]
Sure but please leave OpDiv for my learning!

**Comment by jaebaek** [comment]
For OpSelect .. when I input

         %const_true = OpConstantTrue %bool
       %main = OpFunction %void None %3
          %5 = OpLabel
         %32 = OpSelect %float %const_true %float_1 %float_2
         %31 = OpCompositeConstruct %v4float %float_1 %float_1 %float_1 %32
         %29 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %29 %31
               OpReturn
               OpFunctionEnd

it output

         %24 = OpConstantComposite %v4float %float_1 %float_1 %float_1 %float_1
       %main = OpFunction %void None %6
         %20 = OpLabel
         %23 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %23 %24
               OpReturn
               OpFunctionEnd

Does it mean constant folding for OpSelect is already done?

**Comment by s-perron** [comment]
Considering this done until we find more opportunities that matter.
