### ISSUE TITLE
Opt: Should process entry point call trees and params

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/SPIRV-Tools#760]
Currently the "size reduction"/propagation passes only process entry point functions. This is because it is assumed that the user will first call exhaustive inlining which (usually) gets rid of all function calls in entry point functions.

For opaque propagation needed by glslang, we will not necessarily be doing exhaustive inlining, and may only inline those calls in the entry point call tree that are required to be inlined because they pass opaque types.

So these passes will need to process all functions in the entry point call tree, not just the entry point.

This also means that these passes will need to deal with one new instruction that they have not dealt with until now: OpFunctionParameter (aka params). Of most impact, references to these can show up anywhere an OpVariable reference can show up, which means the code in these passes that deal with access chains and load/store analysis will need to expect and handle them.

For the moment we will only aim for stability and correctness. References of params do not necessarily need to be optimized to allow for the required opaque propagation. However, if at some point it becomes interesting to optimize these references, it can be added.

**Comment by greg-lunarg** [comment]
Claimed by @greg-lunarg

**Comment by dneto0** [comment]
Two comments:

- The code transforms would benefit *all* functions.  It's probably simpler to just apply them everywhere, not just those reachable from an entry point.   I'm not concerned about wasting time on unreachable functions.  Those won't show up in the common case for graphics shaders since linkage is not enabled for graphics APIs.

- About optimizing OpFunctionParameter:   It's wrong to *remove* an OpFunctionParameter.  The OpFunction description says "Add a function. This instruction must be immediately followed by one OpFunctionParameter instruction per each formal parameter of this function. "  So in short we can do everything we normally do for an OpVariable in Function storage class *except* remove the OpFunctionParameter.

(Thanks for filing this!.  I'll triage it.)

**Comment by greg-lunarg** [comment]
Well, for good or ill, I have already pretty much written the code to process all and only entry point call tree functions. I was worried about the additional compile/optimization time spent optimizing functions that were no longer called, especially after exhaustive inlining. The other way to avoid this was add a dead function elimination pass. But I was worried that people might forget to call it. If all the passes only process functions in the call tree, then we automatically will optimize the functions that are called and won't spend time optimizing functions that are not called. So it seemed like the best course. Its just three dozen lines of code. If you really think it is a bad idea, I am willing to walk away from it.

Re Params, yes, we cannot delete them. I will add a test to make sure that unused ones will not be deleted.

**Comment by greg-lunarg** [comment]
PS. Ultimately I do want to put a dead function elimination pass in spirv-opt.

**Comment by dneto0** [comment]
No worries.  I'll take any forward progress I can get.   People who want more are free to contribute patches to make it so.  :-)

I'm very much ok with people having slow flows when they inject useless code into the pipeline.  It's self-limiting and hopefully self-correcting behaviour.   I'll trade that off for slightly more simple code.  But you're already done, so yay.

**Comment by dneto0** [comment]
WIP: https://github.com/KhronosGroup/SPIRV-Tools/pull/762

**Comment by dneto0** [comment]
BTW, the "process entry-point call tree" changes are a nice cleanup.  So bravo.  :-)

**Comment by greg-lunarg** [comment]
Can be closed as of #762
