### ISSUE TITLE
Add a module linker (combine contents of multiple modules)

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Tools#768]
@pierremoreau has claimed this and is very far along.  See https://github.com/KhronosGroup/SPIRV-Tools/pull/693
Creating this issue to track it on the projects page.

**Comment by LoopDawg** [comment]
@johnkslang pointed me to this issue.  I was (very tentatively) thinking about a module merger tool, but to a quick glance, it looks like there would be a lot of overlap with this linker, so the motivation for it may be covered or nearly covered by this.

Does the linker handle:

 (1) Eliminating logically identical functions when the IDs within the functional duplicates are different between module A and module B?  I believe this comes up sometimes when ubershaders are baked down.

(2) Introduction of multiple entry points into the linked result?  E.g, if standalone modules A and B are linked, then the result would contain AEntryPoints() and BEntryPoints()?

Related random thought: the current spirv-remap tool was constrained (by request, to ease integration into existing toolchains) to not look across modules, and to produce valid SPIRV modules, both of which limit its effectiveness.  Some of the underpinnings one would want for (1) above, and the similar in spirit redundant type elimination I believe this linker already does, are the same ones you might imagine for multi-module-scoped ID remapping.  However, I don't know if both things would be useful to have.  If you can merge modules, why not do that and eliminate redundancies for real, rather than fall back on a compressor dictionary with its potential horizon limits etc?

Perhaps some in-house toolchain couldn't handle multiple entry point modules.  Or perhaps there's still enough win from similar but not redundant code.  Still, it seems like the case for looking across modules gets weaker, once modules can be merged.

Also related: un-baking, and specialization constants.

**Comment by dneto0** [comment]
Answering:

No to (1).   Eliminating logically redundant functions could be delivered as a code transform pass, available in spirv-opt (and underlying API).   I filed #805 to track that as a separate task.

Yes to (2).   
I just realized that entry point names can collide.  I don't know if the linker errors out, but it should.  Also, GLSL shaders are always named "main" by default.  I believe Glslang lets you set the name of the entry point when compiling for HLSL but not for GLSL.  (That seems an oversight.)

I agree that merging modules increases the opportunity for eliminating redundant code.  !

Vulkan conformance tests cover the case of multiple entry points in the same module.  So at least drivers should handle it.

**Comment by pierremoreau** [comment]
The linker already errors out if there are multiple entry points of the same type and with the same name, or multiple entry points with the same name but of different types (see https://github.com/pierremoreau/SPIRV-Tools/blob/implement_linker/test/link/entry_points_test.cpp).

**Comment by LoopDawg** [comment]
OK, thanks!  Agreed about an identical fn removal optimization.

About name collisions: my tentative thinking for module merging aimed at redundancy elimination was that collisions would be common in real world cases, but that a disambiguation mechanism could be supplied.  If not already de-collided at compile time, it could be a user supplied mapping, and/or procedural substitution such as appending the module name to the entry point names.

**Comment by dneto0** [comment]
#693 has been merged.  It's usable now.  It has a few things to address but was better to merge now as "under development".

I'll keep this open until my "required feedback" is addressed.

**Comment by dneto0** [comment]
> The linker already errors out if there are multiple entry points of the same type and with the same name, or multiple entry points with the same name but of different types (see https://github.com/pierremoreau/SPIRV-Tools/blob/implement_linker/test/link/entry_points_test.cpp).

I think you said that incorrectly.  The tests (at https://github.com/KhronosGroup/SPIRV-Tools/blob/master/test/link/entry_points_test.cpp ) are:
 - same execution model, different name --> link success
 - different execution model, same name --> link success
 - same execution model, same name --> link failure

That's the right set of results.

About link-time disambiguation: I think there's a usability problem with this.  If the linker does the resolving, how does a client know which symbols from which modules were remapped.   I think it's better to make the client do the disambiguation first so they keep the rest of their internal bookkeeping straight.

**Comment by dneto0** [comment]
Fixed by #1149

This is a great addition!  Thank you @pierremoreau

**Comment by pierremoreau** [comment]
> I think you said that incorrectly. The tests (at https://github.com/KhronosGroup/SPIRV-Tools/blob/master/test/link/entry_points_test.cpp ) are:
>
>    same execution model, different name --> link success
>    different execution model, same name --> link success
>    same execution model, same name --> link failure
>
>That's the right set of results.

Ugh, yes, that is the right set of results indeed.

>About link-time disambiguation: I think there's a usability problem with this. If the linker does the resolving, how does a client know which symbols from which modules were remapped. I think it's better to make the client do the disambiguation first so they keep the rest of their internal bookkeeping straight.

Reading the spec again, it feels like the linker should disambiguate between different symbols with the same name using the symbol’s signature. If the signature are the same, I agree that the client should do the disambiguation (symbol’s name should be “unique”).
Currently the linker will fetch, for each imported symbol, all exported symbols with the same name. If there are 0 or more than 1 matches, it will error out. Then it will check the signatures and error out if they do not match. I believe it should instead: 1) make a list of all exported symbols with the same name and signature, 2) error out if there are 0 or more than 1 matches.
