### ISSUE TITLE
Request for more intelligible Disassembly output

### ISSUE THREAD

**Issue by paniq** [KhronosGroup/SPIRV-Tools#788]
I use spirv-dis a lot to fix validation errors. I greatly appreciate the color coding. Yet I find the output generated by spirv-dis a little difficult to read, compared to reading LLVM IR. I understand that the output is supposed to be valid parseable text, so here are two small suggestions that would improve readability a great deal while not breaking parsing rules:

(We assume no beginning indentation / text centering for the following rules)

* All instructions inbetween `OpFunction` and `OpFunctionEnd` are indented by 4 spaces, except `OpLabel` instructions. This allows the reader to quickly visually parse block boundaries.
* Every `OpFunction` instruction is preceeded by an extra newline, to allow the reader to quickly visually parse function boundaries.

In case that parseability is no concern (perhaps a special mode), I would appreciate it if decorators, constants and references to types could be directly inlined. I find myself constantly jumping back and forth between instructions and declarations, and that renders debugging validation errors more cumbersome than it needs to be.

Thank you for your time.

**Comment by dneto0** [comment]
I sympathize.  I stare at a lot of diassembly too!

Thanks for the thoughtful suggestions.

- Gaps between main sections.  I agree inserting gaps between functions would make it easier to read.  I tend to do that manually in an editor, but it would be better if automatic.  I also tend to insert a gap before decorations, before types-and-constants.  I hope you'd find that useful too.

- Extra indents within basic blocks.  Yes that would be good.   I'm unsure of how to deal with indenting the SSA-assignments within a block through.  See below:

Here's a mockup of a sample code (from a bug I've filed).  I've put in gaps, and indented within a block.
The extra indents don't help too much.
```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %1 "main"
               OpSource OpenCL_C 120

       %bool = OpTypeBool
       %true = OpConstantTrue %bool
      %false = OpConstantFalse %bool
       %void = OpTypeVoid
          %6 = OpTypeFunction %void

          %7 = OpFunction %void None %6
          %8 = OpLabel
              %9 = OpCopyObject %bool %true
                   OpSelectionMerge %10 None
                   OpBranchConditional %true %10 %10
         %10 = OpLabel
             %11 = OpPhi %bool %9 %8
                   OpReturn
               OpFunctionEnd

          %1 = OpFunction %void None %6
         %12 = OpLabel
                   OpBranch %13
         %13 = OpLabel
             %14 = OpCopyObject %bool %false
             %15 = OpFunctionCall %void %7
                   OpLoopMerge %16 %13 None
                   OpBranchConditional %true %13 %16
         %16 = OpLabel
                   OpReturn
               OpFunctionEnd
```
Perhaps this is better, where the assignments all have their equals signs lined up but the extra indents occur after the equals:
```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %1 "main"
               OpSource OpenCL_C 120

       %bool = OpTypeBool
       %true = OpConstantTrue %bool
      %false = OpConstantFalse %bool
       %void = OpTypeVoid
          %6 = OpTypeFunction %void

          %7 = OpFunction %void None %6
          %8 = OpLabel
          %9 =     OpCopyObject %bool %true
                   OpSelectionMerge %10 None
                   OpBranchConditional %true %10 %10
         %10 = OpLabel
         %11 =     OpPhi %bool %9 %8
                   OpReturn
               OpFunctionEnd

          %1 = OpFunction %void None %6
         %12 = OpLabel
                   OpBranch %13
         %13 = OpLabel
         %14 =     OpCopyObject %bool %false
         %15 =     OpFunctionCall %void %7
                   OpLoopMerge %16 %13 None
                   OpBranchConditional %true %13 %16
         %16 = OpLabel
                   OpReturn
               OpFunctionEnd
```
Is that second option better?

About decorations:  I find decorations are the most painful thing because they are non-local(!).   It makes it harder to read *and* deal with in code.   A special mode is an interesting idea.  Can you add a comment below showing the kind of thing you'd like to see?   How would you deal with decoration groups? (Not many compilers deal with decoration groups, but SPIRV-tools has to manage them of course.)

Thanks again for the helpful feedback and suggestions!

**Comment by ShabbyX** [comment]
The second option looks better to me. I would also suggest indenting blocks as you would in C, as in nested blocks are indented more (then OpLabel can be aligned with the block, which may be better?). I think it's probably best to have these formatting be done under a command line flag, so if there are users who parse the output of `spirv-dis(1)` they wouldn't be affected.

**Comment by dj2** [comment]
I did some experiments and didn't find the indenting that useful. The separation with blank lines was a lot more useful in adding the reading of the disassembly, at least for me.

**Comment by ShabbyX** [comment]
I had this open in a tab for 3 years, finally got around to actually doing something.

Since https://github.com/KhronosGroup/SPIRV-Tools/pull/5671, you should be able to use `--nested-indent` to get nesting, `--reorder-blocks` to make the SPIR-V follow the natural structure of the shader (instead of seeing the assembly in the order it's in the binary). An earlier comment also made `--comment` more useful.

I'm going to close this as done, but if you have other ideas, please open a new issue (and tag me, I'm quite interested)
