### ISSUE TITLE
Extend constant folding to do arithmetic simplifications

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#896]
This is a pre-requisite for #889.

Currently, a constant folding library exists for integer types (https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/fold.cpp).  This will need to be extended to fold floating point expressions and other simplifications (e.g., %21 - %21 folds to 0 for any integer result ID).

With the current implementation, we can get some of the required behaviour for SSA-CCP, but this folding helper will need to be extended.

**Comment by dneto0** [comment]
- [ ] If all value operands of a Phi %phi are value %x, and %phi is not %x, then replace all uses of %phi with %x

**Comment by dneto0** [comment]
- [ ] Undef absorption.  See #710

**Comment by s-perron** [comment]
@dneto0 I think we did everything except for the undef absorption.  Since there is #710 is opened for that, 

@dnovillo Do you have specific simplifications that you want done?  Can they be listed here so we can know when we are done?  Otherwise, I would like to close this.  We have the ability to add the constant folding rules that we want.  A few are implemented.

**Comment by s-perron** [comment]
Marking as done.  We have the infrastructure to get this done, and we can do most of the obvious stuff.  If we want to do anything specific open a new issue with an example.
