### ISSUE TITLE
Unify all the DCE passes into a single pass

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Tools#906]
spirv-opt has more than a handful of DCE (Dead Code Elimination) passes.  This makes it difficult to use and potentially slow, as every little pass implies a new IR scan.

We should aggregate all these passes into a single DCE pass that handles all the various cases.

**Comment by s-perron** [comment]
I think we should take the algorithm in aggressive dead code elimination and apply it to the entire module, including the code not in functions, at once.  That should be able to remove the global variables, types, constants, etc. that are unused all in one pass.

Because labels and function definitions are instructions with results, removing dead basic-blocks and dead functions could be part of this as well.  However, I don't think it should because deleting them is very different--it is not removing a single instruction.

**Comment by alan-baker** [comment]
Fixed by 3a054e1ddcc43cde3fdcb906ae087b2aa39d1deb.
