### ISSUE TITLE
spirv-val invalid on glslangvalidator generated spv file for opGroupXNonUniformAMD

### ISSUE THREAD

**Issue by aurolou** [KhronosGroup/SPIRV-Tools#991]
When generating the spv file with glslangvalidator from the glsl file and then validating the generated spv file with spirv-val, "Operand 4 of GroupXNonUniformAMD requires one of these capabilities: Kernel", is returned for the add/min/maxInvocationsNonUniformAMD functions.
[shader.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/1496606/shader.zip)

**Comment by dneto0** [comment]
The SPV_AMD_shader_ballot extension clearly intends to use group operations because the new instructions are useless without group operations.  The extension spec should say to add the extension as an additional enabling condition for the group operation.

GL_AMD_shader_ballot says that Reduce, InclusiveScan, ExclusiveScan are usable. 
I'll fix the validator to match the intent.

**Comment by dneto0** [comment]
Fixed with #1015
